### ISSUE TITLE
What convention do PyRanges objects follow: 0-based or 1-based?

### ISSUE THREAD

**Issue by hpages** [biocore-ntnu/pyranges#101]
In the _0-based convention_ (used by the BED format) the range that spans the first 10 bases of a chromosome is represented by setting start-end to 0-10 (end position is excluded). In the _1-based convention_ (used by the GTF and GTF3 formats and in Bioconductor) this range is represented by setting start-end to 1-10.

I couldn't find anything in PyRanges documentation about which convention is used.

Note that the following result:
```
>>> import pyranges as pr
>>> x = pr.PyRanges(chromosomes='chr1', starts=[10], ends=[20])
>>> y = pr.PyRanges(chromosomes='chr1', starts=[20], ends=[30])
>>> x.intersect(y)
Empty PyRanges
```
suggests that the _0-based convention_ is used. With the _1-based convention_, this intersection wouldn't be empty (it would contain exactly one base).

But OTOH the following result:
```
>>> print(x.to_gff3())
chr1	.	.	10	20	.	.	.	
```
suggests the opposite!

Also note that having a PyRanges method that returns the number of bases in each range (_width_ in Bioconductor terminology) would be very useful. Right now, given that it's not clear which convention is used, one has no way to know whether the _width_ should be computed with `x.End - x.Start` (_0-based convention_) or with `x.End - x.Start + 1` (_1-based convention_).

Thanks!
H.

PS: FWIW I started a small Bioconductor package to facilitate access to PyRanges objects from Bioconductor: https://github.com/hpages/BiocPyRanges

**Comment by endrebak** [comment]
All of Python is zero-based so what you have reported is a bug, thanks :)

Do you have an immediate use-case yourself for BiocPyRanges? It seems to me like the Bioconductor project is much more feature-rich so I guess there are less things you can do with PyRanges than GenomicRanges. But cool anyways :)

**Comment by hpages** [comment]
> All of Python is zero-based so what you have reported is a bug, thanks :)

But then "Start" is kind of a misnomer.  When we say that a transcript "starts" at position 10 on the positive strand of chr1, we really mean that the TSS is the 10th base of chr1, not the 11th base! The "Start" in your case is actually an offset and IMO naming it "Start" has the potential to be an endless source of confusion and errors. This is why the UCSC folks only use the 0-based convention _internally_ (i.e. at the C level) but what they display on their Genome Browser are the 1-based positions.

So sure, it makes a lot of sense to use zero-based indexing for PyRanges objects internally (that's what Python uses, so not a choice anyway) but wouldn't it be possible to provide a PyRanges high-level API that uses the 1-based convention? For example the constructor would take 1-based starts and ends, and the print method would display these 1-based positions in the "start" and "end" columns. I guess that also means that `start()` and `end()` accessors would need to be provided (the former would return `x.Offset + 1` and the latter `x.End`). 

Also what do you think of adding a `width()` accessor for PyRanges objects?

> Do you have an immediate use-case yourself for BiocPyRanges?

Not really. Just wanted to play around a little with **reticulate** and learn how to interact with Python objects from R. PyRanges objects seemed like a good place to start.

**Comment by stephenkraemer** [comment]
I think its really cool that you offer some feedback based on your invaluable experience with GenomicRanges+Co. However, as a user of pyranges coming from python/C, I would find switching to 1-based coordinates inconvenient (and I do find it incovenient, everytime I use R). BED files, for example, are also a widespread standard, and use 0-based, right open intervals. Once I export the Start and End columns from a PyRanges object into a dataframe, as a python user, I personally would expect them to adhere to BED/python slicing conventions in my downstream processing. Just to give a user perspective, it's very well possible that I am missing the bigger picture here..

**Comment by hpages** [comment]
1-based starts/ends is the universal language spoken in the Bioinformatics community, not just in R/Bioconductor. Again, for most bioinformaticians, saying that a gene is at "chr1:10-1000" means that it **starts** on the 10th base, not that its **offset** is 10 bases. So maybe it's just a matter of clarifying the terminology in PyRanges' documentation. Thanks!

**Comment by endrebak** [comment]
@hpages Thanks for the feedback. I appreciate any you might have :) Also thanks for coming up with GenomicRanges - I consider it the most useful genomics-exclusive data structure.

This does the same as what you propose `width()` should do, as far as I can see:

```
import pyranges as pr
gr = pr.data.f1()
gr.width = gr.lengths()
# +--------------+-----------+-----------+------------+-----------+--------------+-----------+
# | Chromosome   |     Start |       End | Name       |     Score | Strand       |     width |
# | (category)   |   (int32) |   (int32) | (object)   |   (int64) | (category)   |   (int32) |
# |--------------+-----------+-----------+------------+-----------+--------------+-----------|
# | chr1         |         3 |         6 | interval1  |         0 | +            |         3 |
# | chr1         |         8 |         9 | interval3  |         0 | +            |         1 |
# | chr1         |         5 |         7 | interval2  |         0 | -            |         2 |
# +--------------+-----------+-----------+------------+-----------+--------------+-----------+
# Stranded PyRanges object has 3 rows and 7 columns from 1 chromosomes.
# For printing, the PyRanges was sorted on Chromosome and Strand.
```

I agree with you about the importance of making sure people understand these are zero-based intervals. Hackers with Python-experience would likely expect that, but bioinformaticians in generalx might not. I am now contemplating adding it to the info-string below the PyRanges, which you can see in the example I posted.

I also pushed a fix for the 1-indexing of gtf/gff:

* when a gtf/gff3 is read a 1 is deducted from Start
* when written, a 1 is added to Start.

Unless you have further thoughts I guess we can closes this issue. Thanks again.

**Comment by hpages** [comment]
Great improvements! The `width` column helps clarify the situation a lot. Thanks for fixing the gtf/gff stuff.
