### ISSUE TITLE
Set-like not?

### ISSUE THREAD

**Issue by tzuni** [biocore-ntnu/pyranges#102]
So I had the need recently to do some set-like subtraction between range objects. The existing subtract removes the overlapping sections of reads, thereby adjusting the resulting range starts and ends to remove parts which overlapped the subtracted ranges.

What I needed though was, given 2 range objects gr1 and gr2, entirely remove ranges in gr1 which overlapped ranges in gr2 at all. I can do this without much trouble, but it seems like a computationally inefficient way to go about it:

```
gr1 = pr.PyRanges(pd.DataFrame({
    'Chromosome': ['chr1', 'chr1', 'chr1'],
    'Start': [10, 100, 200],
    'End': [50, 180, 220]
}))

gr2 = pr.PyRanges(pd.DataFrame({
    'Chromosome': ['chr1', 'chr1', 'chr1'],
    'Start': [10, 60, 210],
    'End': [50, 90, 260]
}))

def a_not_b(gr1, gr2):
    '''
    Remove ranges in gr1 which overlap ranges in gr2.
    '''
    tmp = gr1.join(gr2)
    return gr1.subtract(tmp)

a_not_b(gr1, gr2)
+--------------+-----------+-----------+
| Chromosome   |     Start |       End |
| (category)   |   (int32) |   (int32) |
|--------------+-----------+-----------|
| chr1         |       100 |       180 |
+--------------+-----------+-----------+
Unstranded PyRanges object has 1 rows and 3 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
```
Maybe it would be nice to be able to do something like this instead `gr1.not(gr2)`? With perhaps some optional arguments `min_overlap` to adjust the minimum overlap required to cause a match and `slop` to first expand the ranges in gr1.

**Comment by endrebak** [comment]
Thanks for creating an issue. This should be efficient: `gr1.overlap(gr2, invert=True)`. I guess it is not documented so keeping this open as a reminder.

**Comment by tzuni** [comment]
Ah, yes thank you for pointing that out!

On a related note, I was using `overlap()` to find ranges that overlapped those in a second set. After working with it a little though it would also be important to note that ranges from the first set could be duplicated in the result set if they overlap multiple ranges from the second set. 

This was undesirable in my case though I'm not sure what should be the default behavior. It would be nice to add an argument to toggle this behavior. For now I'm just using a `drop_duplicate_positions` immediately after.

**Comment by endrebak** [comment]
I guess that is undesireable. I guess `gr.overlap(gr2, how=«first»)` should be the default behavior? I wonder what bedtools does 🤔

**Comment by endrebak** [comment]
I changed overlap to only report one interval in 0.0.71 :)
