### ISSUE TITLE
UnboundLocalError in Stats MCC

### ISSUE THREAD

**Issue by GrantDaly** [biocore-ntnu/pyranges#107]
In Pyranges v'0.0.69'

This error was reported when I tried to use the "mcc" function in the "stats" package. It seems to run when I do not include the "genome" option, but I understand that this leads to unreliable results.

### Calling code
chromsizes = pr.data.chromsizes()
mcc = pr.stats.mcc([hypPeaks, huvecBed], labels="SnpChip Motif".split(), genome=chromsizes, strand=False)

### Traceback from Jupyter Notebook
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-22-53da907a8d06> in <module>
      1 chromsizes = pr.data.chromsizes()
----> 2 mcc = pr.stats.mcc([hypPeaks, huvecBed], labels="SnpChip Motif".split(), genome=chromsizes, strand=False)
      3 # tempPyRangeHyp.stats.jaccard(huvecBed)

~/anaconda3/lib/python3.7/site-packages/pyranges/statistics.py in mcc(grs, genome, labels, strand, verbose)
    238                 return pd.concat([df, df2])
    239 
--> 240         genome = genome.apply(make_stranded)
    241         genome_length = genome.length
    242     else:

UnboundLocalError: local variable 'make_stranded' referenced before assignment

### Running with no chromosome sizes seems to run

mcc = pr.stats.mcc([hypPeaks, huvecBed], labels="SnpChip Motif".split(), strand=False)

<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>T</th>\n      <th>F</th>\n      <th>TP</th>\n      <th>FP</th>\n      <th>TN</th>\n      <th>FN</th>\n      <th>MCC</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>3</th>\n      <td>Motif</td>\n      <td>Motif</td>\n      <td>38573435</td>\n      <td>0</td>\n      <td>155869907</td>\n      <td>0</td>\n      <td>1.000000</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Motif</td>\n      <td>SnpChip</td>\n      <td>3234793</td>\n      <td>155869907</td>\n      <td>0</td>\n      <td>35338642</td>\n      <td>-0.947372</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>SnpChip</td>\n      <td>Motif</td>\n      <td>3234793</td>\n      <td>35338642</td>\n      <td>0</td>\n      <td>155869907</td>\n      <td>-0.947372</td>\n    </tr>\n    <tr>\n      <th>0</th>\n      <td>SnpChip</td>\n      <td>SnpChip</td>\n      <td>159104700</td>\n      <td>0</td>\n      <td>35338642</td>\n      <td>0</td>\n      <td>1.000000</td>\n    </tr>\n  </tbody>\n</table>

**Comment by endrebak** [comment]
Ah, I will look into it. Thanks :)

**Comment by endrebak** [comment]
Should be fixed in 0.0.71 which I merge and upload later today :)
