### ISSUE TITLE
ModuleNotFoundError is unavailable in python 3.5

### ISSUE THREAD

**Issue by Hoeze** [biocore-ntnu/pyranges#108]
Could we replace in line https://github.com/biocore-ntnu/pyranges/blob/f2ffd5bbb4aeff3411c7b78467b1787404beadbc/pyranges/__init__.py#L6
with 
```python3
except ImportError:
```
?

ModuleNotFoundError is not available with python 3.5.
ImportError should be enough anyways.

**Comment by endrebak** [comment]
Yes, sorry! Thanks for pointing it out. Will fix in a few hours. I should add py3.5 to Travis :)

**Comment by endrebak** [comment]
Uploading 0.0.71 today which fixes this :)

**Comment by endrebak** [comment]
Should be good now :) https://github.com/biocore-ntnu/pyranges/blob/master/pyranges/__init__.py#L6

**Comment by Hoeze** [comment]
Thanks for fixing @endrebak !
