### ISSUE TITLE
to_gtf 1 based coordinates

### ISSUE THREAD

**Issue by peterch405** [biocore-ntnu/pyranges#119]
I have been working with GTF files using the `pr.read_gtf(file)`

Pyranges uses 0-based coordinates and GTF files are 1-based. I would have expected on import for pyranges to do start-1. 

I am trying to get introns from exons using `gtf_gr.features.introns(by='gene')` but because its doing a 0-based operation on 1-based coordinates I think the results are strange:

```
Chromosome    Start      End Strand gene_name  Count  Source Feature Score 
3          1  3466587  3466687      +    Gm1992    1.0  havana    exon     .   
4          1  3466687  3513405      +    Gm1992    NaN  havana  intron     .   
5          1  3513405  3513553      +    Gm1992    1.0  havana    exon     .   
```
I would expect in a 1-based coordintes system for the intron coordinates to be:

```
Chromosome    Start      End Strand gene_name  Count  Source Feature Score 
3          1  3466587  3466687      +    Gm1992    1.0  havana    exon     .   
4          1  3466688  3513404      +    Gm1992    NaN  havana  intron     .   
5          1  3513405  3513553      +    Gm1992    1.0  havana    exon     .   
```

In a 0-based it would be:

```
Chromosome    Start      End Strand gene_name  Count  Source Feature Score 
3          1  3466586  3466687      +    Gm1992    1.0  havana    exon     .   
4          1  3466687  3513404      +    Gm1992    NaN  havana  intron     .   
5          1  3513404  3513553      +    Gm1992    1.0  havana    exon     .   
```
I've been trying to get my head around this, sorry if I am misunderstanding something. To get the correct result should I just do `start+1` and `end-1` for the introns?

**Comment by peterch405** [comment]
Sorry, just noticed you fixed this already. I updated to the newest version. Thank you!

**Comment by endrebak** [comment]
Nothing to apologize for! I appreciate all feedback :)
