### ISSUE TITLE
Feature request: getfasta option

### ISSUE THREAD

**Issue by wdecoster** [biocore-ntnu/pyranges#121]
I can, of course, get this done with pybedtools, but I wonder if it would be hard or of interest to include a getfasta method/command in pyranges.
For reference: https://bedtools.readthedocs.io/en/latest/content/tools/getfasta.html

The objective would be to get, given a pyranges object and a genome fasta, those sequences in the pyranges object.

Also, pyfaidx exists which could be used (https://pypi.org/project/pyfaidx/). It would definitely not be too hard for me to use the df and sequentially using pyfaidx to get my fasta records, but I wondered if you had a better approach in mind.

What do you think?

**Comment by endrebak** [comment]
I have been thinking about this.

```
# Return an array of sequences
sequences = pr.get_fasta(gr, path)
gr.sequences = pr.get_fasta(gr, path)
```

Is there any other functionality from biopython (seq) or pyfaidx you would like to have? 

I would not have pyfaidx as a required dep, but something users could install themselves if they needed the `get_fasta` functionality.

**Comment by wdecoster** [comment]
Looks like that would work for my case

> Is there any other functionality from biopython (seq) or pyfaidx you would like to have?

Not today :)

**Comment by endrebak** [comment]
This was actually on my literal todo list for a long time, but I removed it since I personally had no immediate use for it :)

**Comment by wdecoster** [comment]
I'll let you know if I think of other things like "oh that would be cool if pyranges could do that" ;-)

> I would not have pyfaidx as a required dep, but something users could install themselves if they needed the get_fasta functionality.

Fair enough!

**Comment by endrebak** [comment]
Does it make sense to fetch the complimentary sequence if the strand is reverse?

**Comment by wdecoster** [comment]
Oh maybe it does, perhaps optionally?

**Comment by endrebak** [comment]
I think I should just fetch the sequences and let users complement them based on strand afterwards.

**Comment by endrebak** [comment]
Seems to work:

```

import sys
import pyranges as pr
import pandas as pd

def get_fasta(gr, path):


    """Get fasta sequence.

    Parameters
    ----------
    gr : PyRanges or DataFrame

        Coordinates. Must have columns "Chromosome", "Start", "End", "Strand".

    path : str

        Path to fasta file

    Returns
    -------
    Series

        Sequences, one per interval.

    Warning
    -------

    Note that the names in the fasta header and gr must be the same.

    Examples
    --------

    >>> gr = pr.from_dict({"Chromosome": ["chr1", "chr1"],
    ...                    "Start": [5, 0], "End": [8, 5]})

    >>> gr
    +--------------+-----------+-----------+
    | Chromosome   |     Start |       End |
    | (category)   |   (int32) |   (int32) |
    |--------------+-----------+-----------|
    | chr1         |         5 |         8 |
    | chr1         |         0 |         5 |
    +--------------+-----------+-----------+
    Unstranded PyRanges object has 2 rows and 3 columns from 1 chromosomes.
    For printing, the PyRanges was sorted on Chromosome.

    >>> tmp_handle = open("temp.fasta", "w+")
    >>> _ = tmp_handle.write("> chr1\\n")
    >>> _ = tmp_handle.write("ATTACCAT")
    >>> tmp_handle.close()

    >>> seq = pr.get_fasta(gr, "temp.fasta")

    >>> seq
    0      CAT
    1    ATTAC
    dtype: object

    >>> gr.seq = seq
    >>> gr
    +--------------+-----------+-----------+------------+
    | Chromosome   |     Start |       End | seq        |
    | (category)   |   (int32) |   (int32) | (object)   |
    |--------------+-----------+-----------+------------|
    | chr1         |         5 |         8 | CAT        |
    | chr1         |         0 |         5 | ATTAC      |
    +--------------+-----------+-----------+------------+
    Unstranded PyRanges object has 2 rows and 4 columns from 1 chromosomes.
    For printing, the PyRanges was sorted on Chromosome.
    """

    try:
        import pyfaidx
    except ModuleNotFoundError as e:
        print("pyfaidx must be installed to get fasta sequences. Use `conda install -c bioconda pyfaidx` or `pip install pyfaidx` to install it.")
        sys.exit(1)

    fasta = pyfaidx.Fasta(path, read_ahead=int(1e5))

    seqs = []
    for k, df in gr:
        _fasta = fasta[k]

        for start, end in zip(df.Start, df.End):
            seqs.append(_fasta[start:end].seq)

    return pd.concat([pd.Series(s) for s in seqs]).reset_index(drop=True)
```

I'm in the middle of writing docs so not making any new commits until I am done :)

**Comment by endrebak** [comment]
Note to self: https://github.com/btwael/superstring.py

Ps. the above function can be copy-pasted into your code.

But 0.0.77 has `pr.get_fasta` included.

**Comment by wdecoster** [comment]
ah great!
