### ISSUE TITLE
Do the new docs look bad for anyone else?

### ISSUE THREAD

**Issue by endrebak** [biocore-ntnu/pyranges#123]
Here is how I see them locally:

![Screen Shot 2020-03-24 at 17 33 06](https://user-images.githubusercontent.com/17778898/77452100-d79c9600-6df5-11ea-9c63-9a53ad099cfd.png)

They absolutely do not look right on github pages: https://biocore-ntnu.github.io/pyranges/

**Comment by endrebak** [comment]
I will try readthedocs.

**Comment by wdecoster** [comment]
I miss your old documentation already! :-D

**Comment by endrebak** [comment]
Now the docs look good:

https://biocore-ntnu.github.io/pyranges/autoapi/pyranges/index.html

In my new docs, everything is documented, with examples. Read through them and you will know everything there is to know :) 

I guess I also should have longer guides or example scripts.

Is there anything in particular you miss about the old docs?

**Comment by endrebak** [comment]
Stable at rtd: https://pyranges.readthedocs.io/

Should by subscription to get rid of the ads.

**Comment by wdecoster** [comment]
I can't see the rtd page?

**Comment by endrebak** [comment]
This works: https://pyranges.readthedocs.io/en/master/ right? Strange...

**Comment by wdecoster** [comment]
'master' works, 'latest' doesn't...

![image](https://user-images.githubusercontent.com/11660522/77642183-87d8de80-6f5d-11ea-869f-8d0f5da1f904.png)
