### ISSUE TITLE
feature request: subset by index or bool array

### ISSUE THREAD

**Issue by jonathanronen** [biocore-ntnu/pyranges#13]
Hey!

Would be lovely to have a full-fledged granges clone in python!

How do you feel about implementing sub-setting of ranges objects by indexing into them, and/or with a bool array? Right now I found the workaround is to go via pandas, i.e.

```python
gtf_df = gtf.as_df()
gtf_df_genes = gtf_df[gtf_df.Feature=='gene']
gtf_genes = pyranges.PyRanges(gtf_df_genes)
```

Would be nice to do this directly on the `PyRanges` object, no? :-)

Thx,
J.

**Comment by endrebak** [comment]
`gr.subset(lambda df: df.Feature == "gene")` should work. Strange that I forgot to put it in the docs...

Thanks for reporting!

**Comment by endrebak** [comment]
It is actually hidden away in the docs: https://biocore-ntnu.github.io/pyranges/piping-pyranges.html

**Comment by endrebak** [comment]
In 0.0.47 you can subset on rows using [] too:

```
import pyranges as pr

gr = pr.data.cpg()
print(gr[gr.CpG > 50])
```

Thanks for the feature request.
