### ISSUE TITLE
The following specifications were found to be incompatible with your CUDA driver:    - feature:/win-64::__cuda==11.0=0   - feature:|@/win-64::__cuda==11.0=0  Your installed CUDA driver is: 11.0

### ISSUE THREAD

**Issue by DCnev** [biocore-ntnu/pyranges#130]
Tried installing Pyranges with:

import sys
!conda install -c bioconda pyranges

in Jupyter Notebook and the error in the title appears. Is there a way to fix this? Here's the full output from when I ran it.

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

Building graph of deps:   0%|          | 0/3 [00:00<?, ?it/s]
Examining python=3.7:   0%|          | 0/3 [00:00<?, ?it/s]  
Examining pyranges:  33%|###3      | 1/3 [00:00<00:00, 10.53it/s]
Examining @/win-64::__cuda==11.0=0:  67%|######6   | 2/3 [00:00<00:00,  3.60it/s]
Examining @/win-64::__cuda==11.0=0: 100%|##########| 3/3 [00:00<00:00,  5.41it/s]
                                                                                 

Determining conflicts:   0%|          | 0/3 [00:00<?, ?it/s]
Examining conflict for python pyranges:   0%|          | 0/3 [00:00<?, ?it/s]
Examining conflict for __cuda:  33%|###3      | 1/3 [00:00<00:00, 99.99it/s] 
                                                                            

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your CUDA driver:

  - feature:/win-64::__cuda==11.0=0
  - feature:|@/win-64::__cuda==11.0=0

Your installed CUDA driver is: 11.0

Thank you!

**Comment by endrebak** [comment]
Thanks for reporting! Are you on windows?

Does it work if you install outside of a Jupyter Notebook? 

pyranges has nothing to do with CUDA so this is a weird error. And it seems to say that two required versions of CUDA are in conflict with each other.

**Comment by endrebak** [comment]
What about `pip install pyranges`? Does that work?

**Comment by DCnev** [comment]
G'day, cheers for your quick reply.
I am on windows, haven't tried installing it outside of Jupyter yet but when I tried pip install it's gone hours without giving any output

**Comment by endrebak** [comment]
Hmm, weird. I guess if you create a new environment with conda it should install okay...

Some functionality does not work with windows (nearest/cluster), but since you are the second windows user, I should fix that soon... It is a simple fix.
