### ISSUE TITLE
invert argument of the overlap method is ignored.

### ISSUE THREAD

**Issue by scanisius** [biocore-ntnu/pyranges#132]
Setting `invert=True` when calling the `PyRanges.overlap` method still returns the overlapping regions, rather than the non-overlapping ones. Looking at the code, I see that the `invert` argument simply is not passed to the underlying implementation function `_overlap`. I verified that passing `invert=True` to `_overlap` does seem to give the expect result, so this should be easy to fix.

**Comment by endrebak** [comment]
Thanks for reporting! Will fix Monday. This is what happens when code is untested :)

**Comment by endrebak** [comment]
Thanks again for reporting! It is fixed now in 0.0.78.
