### ISSUE TITLE
Introns by transcript overwrites gene_id with transcript_id

### ISSUE THREAD

**Issue by peterch405** [biocore-ntnu/pyranges#134]
Currently `gr.features.introns(by="transcript")` results in the `gene_id` column being overwritten by `transcript_id`

**Comment by endrebak** [comment]
Thanks for reporting! I rely on user feedback to make pyranges better. Will try to fix tomorrow 👍🏻

**Comment by endrebak** [comment]
Should be fixed in 0.0.79. Thanks for reporting :)
