### ISSUE TITLE
Return empty intersections?

### ISSUE THREAD

**Issue by littleblackfish** [biocore-ntnu/pyranges#141]
Hello, thanks for implementing this!

I am trying to compare a list of windows to a list of exons. For each window, not only would I like to get its intersection to any exon, but I also would like to know if a window does not intersect with any exon. It would be very useful if I could do something like `windows.intersect(exons, showempty=True)` so I don't lose strict mapping between windows and intersections. As far as I can see none of the existing options provide this. Am I missing something or is this simply not supported?

**Comment by endrebak** [comment]
This will create a PyRanges object that has a column that tells whether the window overlaps the exons or not.

Close enough? :)

```
overlap = windows.intersect(exons)
no_overlap = windows.intersect(exons, invert=True)

overlap.Overlap = True
no_overlap.Overlap = False

windows = pr.concat([overlap, no_overlap]).sort()
```

**Comment by littleblackfish** [comment]
I am at 0.0.79 and the intersect function does not have an invert argument.

**Comment by endrebak** [comment]
overlap must have an invert then :)

**Comment by littleblackfish** [comment]
I think I might be able to make that work, but it does not address my core issue that the intersections are not mapped to query intervals.

In other words, for example, when I am specifying `how='first'`, I either get 1 intersection or 0, yes? Ideally, I'd like the option to get a new frame with identical index, and empty ranges where there was no intersection.  

Failing that, I at least would like to be able to do this explicitly by iterating and calling intersect row by row. 

I just picked up this library last night, is this contradicting the typical use case?

**Comment by endrebak** [comment]
It is not how I imagined it would be used. How would an empty range look?

PyRanges do not have indexes, the positions are the implicit indices.

**Comment by littleblackfish** [comment]
This is such a shame for me because it is insanely fast and just a tiny bit off from what I need. 

I guess an empty range would have Start==End. 

But okay, let's focus on the alternative approach. Can I iterate a PyRanges row by row without getting into the underlying DataFrame? Can I call intersect on a single row, or do I have to build a single-row PyRanges to be able to do that?

**Comment by endrebak** [comment]
`exons["chr1", 50:600]` intersects without creating a new PyRanges. But this is slow.

I do not see how your approach would work. Take the example:

```
import pyranges as pr
f1 = pr.data.f1()
f2 = pr.data.f2()
f1.intersect(f2) 
+--------------+-----------+-----------+------------+-----------+--------------+
| Chromosome   |     Start |       End | Name       |     Score | Strand       |
| (category)   |   (int32) |   (int32) | (object)   |   (int64) | (category)   |
|--------------+-----------+-----------+------------+-----------+--------------|
| chr1         |         6 |         7 | interval2  |         0 | -            |
+--------------+-----------+-----------+------------+-----------+--------------+
Stranded PyRanges object has 1 rows and 6 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome and Strand.
```

How would your desired result look?

**Comment by littleblackfish** [comment]
It would look something like this : 
```
+--------------+-----------+-----------+------------+-----------+--------------+
| Chromosome   |     Start |       End | Name       |     Score | Strand       |
| (category)   |   (int32) |   (int32) | (object)   |   (int64) | (category)   |
|--------------+-----------+-----------+------------+-----------+--------------|
| chr1         |         None |         None | interval1  |         0 | +            |
| chr1         |         None |         None | interval3  |         0 | +            |
| chr1         |         6 |         7 | interval2  |         0 | -            |
+--------------+-----------+-----------+------------+-----------+--------------+
```

Ore replace Nones with -1 or whatever. Ultimately, I would like to do something like `f1.intersect(f2).lengths()` and get [0,0,1]. 

The problem I have on hand is that I have a bunch of windows, and I'd like to (quickly) get how much of each window is within an exon. I don't think this is **that** niche. 

So if I could do `f1.intersect(f2).lengths()`, then I would divide by `f1.lengths()`, and voila! This is what I mean by matching indexes.

**Comment by endrebak** [comment]
I see what you mean. What about `f1.join(f2, how="left")` and then use techniques from here: https://github.com/biocore-ntnu/pyranges/issues/114

?

I am on vacation now, but will think more about this.

**Comment by littleblackfish** [comment]
Yeah, congrats on the dissertation, well deserved vacation! Summertime in Scandinavia is the best too; one day I'll make it back there!

I can dance with the approach from #114 but it does not cover all the cases. If a window overlaps with more than one exon, join yields more rows than the number of windows. If a window overlaps with no more than 2 exons I can join twice with `keep='first'` and `keep=last` and manually deal with it. If a window overlaps with more than 2 exons I am out of luck, but in my case this should be rare enough to be negligible.

**Comment by endrebak** [comment]
I am open to improving upon this, but I need to think some more. I guess I
could have a version of intersect that returns intervals with -1 for starts
and ends if there are no overlaps, but it might not be the best solution.

You could use my first approach and then set the Starts and Ends in all
windows where the overlap is False to 0 and 0.

**Comment by endrebak** [comment]
Does coverage do what you are looking for?

```
In [15]: f1.coverage(f2)
Out[15]:
+--------------+-----------+-----------+------------+-----------+--------------+------------------+--------------------+
| Chromosome   |     Start |       End | Name       |     Score | Strand       |   NumberOverlaps |   FractionOverlaps |
| (category)   |   (int32) |   (int32) | (object)   |   (int64) | (category)   |          (int64) |          (float64) |
|--------------+-----------+-----------+------------+-----------+--------------+------------------+--------------------|
| chr1         |         3 |         6 | interval1  |         0 | +            |                0 |                0   |
| chr1         |         8 |         9 | interval3  |         0 | +            |                0 |                0   |
| chr1         |         5 |         7 | interval2  |         0 | -            |                1 |                0.5 |
+--------------+-----------+-----------+------------+-----------+--------------+------------------+--------------------+
Stranded PyRanges object has 3 rows and 8 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome and Strand.
```

**Comment by endrebak** [comment]
```
def no_overlap_to_minus1(df):
    df.loc[df.Overlap == False, "Start"] = -1
    df.loc[df.Overlap == False, "End"] = -1
    return df


overlap = windows.intersect(exons)
no_overlap = windows.intersect(exons, invert=True)

overlap.Overlap = True
no_overlap.Overlap = False

result = pr.concat([overlap, no_overlap]).sort().apply(no_overlap_to_minus1)
```

**Comment by littleblackfish** [comment]
Yes! `coverage` seems to be the ticket for me. Single call does the trick, just like I was initially hoping for. Super fast, super clean. 

Many thanks.

**Comment by endrebak** [comment]
Thanks for the discussion and feedback 👍
