### ISSUE TITLE
Incorrect implementation of Fisher's OR

### ISSUE THREAD

**Issue by iamjli** [biocore-ntnu/pyranges#144]
https://github.com/biocore-ntnu/pyranges/blob/97559c8a57836975c2a5bfda228284eb2bdb829b/pyranges/statistics.py#L165

Should be of the form `(n1/n2)/(d1/d2)`

**Comment by endrebak** [comment]
I do not doubt you are correct. How embarrassing! I was just blindly copying another library.

Would you mind bumping `pyranges/version.py` and adding a note to the CHANGELOG? Then I could just merge this into master and upload to PyPI.

**Comment by endrebak** [comment]
Thanks! Now out on pypi :)
