### ISSUE TITLE
Formatting in jupyter

### ISSUE THREAD

**Issue by iamjli** [biocore-ntnu/pyranges#146]
Would be nice if PyRanges objects were displayed similarly to how pandas dataframes are in jupyter notebooks. This kind of thing happens frequently which effectively doubles the height of the output:

![image](https://user-images.githubusercontent.com/7219365/90456911-1d6d3a00-e0c8-11ea-9ddf-f85218f642a7.png)

**Comment by endrebak** [comment]
I never used jupyter, but I see the problem.

pyranges tries to read the console size and set the number of columns displayed based on it (like pd dataframe), but I guess this mechanism breaks down in jupyter for some reason.

**Comment by endrebak** [comment]
Waiting for a reply: https://stackoverflow.com/questions/64391373/how-do-i-find-the-width-of-an-ipython-cell

**Comment by endrebak** [comment]
I am unable to reproduce the issue. 

<img width="1153" alt="Screen Shot 2020-10-20 at 08 23 45" src="https://user-images.githubusercontent.com/17778898/96548204-b6c5f180-12ad-11eb-8c5b-716885a1846c.png">

If anyone experiences this, please do post the steps needed to reproduce.

I guess it might happen if you resize the browser window after starting the notebook.

**Comment by endrebak** [comment]
It works now right? I’ve never used jupyter myself :/
