### ISSUE TITLE
 Columns Chromosome, Start and End must be in the dataframe!

### ISSUE THREAD

**Issue by huhumiily** [biocore-ntnu/pyranges#147]
I received the following error message when testing with pyranges.multioverlap. How can I solve the problem? Thank you!

pr.version.__version__
'0.0.81'

a = '''Chromosome Start End
chr1    6    12
chr1    10    20
chr1    22    27
chr1    24    30'''
b = '''Chromosome Start End
chr1    12    32
chr1    14    30'''
c = '''Chromosome Start End
chr1    8    15
chr1    10    14
chr1    32    34'''

grs = {n: pr.from_string(s) for n, s in zip(["a", "b", "c"], [a, b, c])}
pr.count_overlaps(grs)
Traceback (most recent call last):

  File "<ipython-input-9-395f5621bbc1>", line 15, in <module>
    pr.count_overlaps(grs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyranges\multioverlap.py", line 150, in count_overlaps
    res = features.apply_pair(gr, _count_overlaps, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyranges\pyranges.py", line 766, in apply_pair
    result = pyrange_apply(f, self, other, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyranges\multithreaded.py", line 323, in pyrange_apply
    results = process_results(results, keys)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyranges\multithreaded.py", line 109, in process_results
    gr = pr.PyRanges(results_dict)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyranges\pyranges.py", line 177, in __init__
    _init(self, df, chromosomes, starts, ends, strands, int64, copy_df)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyranges\methods\init.py", line 183, in _init
    )), "Columns Chromosome, Start and End must be in the dataframe!"

AssertionError: Columns Chromosome, Start and End must be in the dataframe!

![无标题](https://user-images.githubusercontent.com/49506159/90466908-7929d880-e145-11ea-8df8-1af378acfc04.png)

**Comment by endrebak** [comment]
Will look into it now :)

**Comment by huhumiily** [comment]
> Will look into it now :)

Thanks，but how should I avoid creating threads？In other words, what can I do to make it work.

**Comment by endrebak** [comment]
I made a mistake in my last update (0.0.81). Fixing it now.

**Comment by huhumiily** [comment]
Thank you very much for your timely feedback and look forward to your correct version release.

 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Endre Bakken Stovner"<notifications@github.com&gt;; 
发送时间: 2020年8月18日(星期二) 下午2:40
收件人: "biocore-ntnu/pyranges"<pyranges@noreply.github.com&gt;; 
抄送: "HU YAN"<568038247@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [biocore-ntnu/pyranges]  Columns Chromosome, Start and End must be in the dataframe! (#147)





 
I made a mistake in my last update (0.0.81). Fixing it now.

**Comment by endrebak** [comment]
0.0.82 out now on pypi :)

**Comment by huhumiily** [comment]
> 0.0.82 out now on pypi :)

It works!Great!
