### ISSUE TITLE
Join with length of overlap

### ISSUE THREAD

**Issue by iamjli** [biocore-ntnu/pyranges#149]
Is there a way to include a column that indicates the amount of overlap (# bp) during the join operation?

The analogous bedtools command would be 

`bedtools intersect -a A.bed -b B.bed -wo`

**Comment by iamjli** [comment]
Just noticed a possible workaround in #114, but perhaps this should be added to the method. I can create a PR if you agree.

**Comment by endrebak** [comment]
Sure! What interface do you propose?

**Comment by iamjli** [comment]
Yup that works. See #150

**Comment by endrebak** [comment]
Thanks for your interest and effort :)
