### ISSUE TITLE
nearest how, on *other* pyrange

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [biocore-ntnu/pyranges#153]
I have a list of ATAC-seq peak summits, and I want to calculate the distance to the closest "promoter". I assume promoters are always upstream of the tss. This means that for each peak, I want to find the closest TSS, but the peak must be upstream of the tss.

How would I go about this? If I do:

```
peaks.nearest(tss)
```

I get the closest tss, but it ignores the directionality of the tss

```
peaks.nearest(tss, how="upstream")
```

Won't work because the direction would be reasoned from the point of view from the peak.

If we were to switch the search around:

```
tss.nearest(peaks, how="upstream")
```

Then we would to do a lot(!) more look ups in my case, and we are not even guaranteed to find the closest tss for each peak.

Does pyranges support this out-of-the-box? If not, any pointers in how to change my approach? I'm having difficulties wrapping my head around and finding a "nice" solution.

**Comment by endrebak** [comment]
I would love to help :) 

Do you have a simple example that shows what you want to achieve and how PyRanges falls short? 

Why would you not be guaranteed to find the closest TSS when using `tss.nearest(peaks, how="upstream")`?

**Comment by endrebak** [comment]
Would doing something like `peaks["+"].nearest(tss["-"])` and vice-versa work in your case?

**Comment by Maarten-vd-Sande** [comment]
Thanks for the reply! I hadn't checked with the `how`since that won't work for me, so I tried making an example but turns out that both pyranges need a Strand for how.

```
peaks = {"Chromosome": [1, 1], 
         "Start": [12, 30], 
         "End": [13, 31]}

tss = {"Chromosome": [1, 1], 
       "Start": [33, 40, 14], 
       "End": [34, 41, 15],
       "Strand": ["+", "+", "-"]}

peaks = pyranges.from_dict(peaks)
tss = pyranges.from_dict(tss)
tss.nearest(peaks, how="upstream")  # <-- won't work
```

My peaks are not "stranded". They are ATAC-seq peaks, and there is (theoretically) no difference in cutting between the strands. So I can't test your proposed solution. Probably what you propose would work without the ["+"] for the peaks though. Let me think about that :thinking: 

What I would like as output is that for peak 1 and 2 the closest tss is the first tss. The third tss has the wrong orientation for the first peak, and for the second peak there is a closer-by tss with a correct orientation.

**Comment by Maarten-vd-Sande** [comment]
I think your proposal would not work, here with a short graphical summary:

```
>----->   |  <-----<    >----->
```

The two closest TSS are both facing the wrong directions, the third arrow is the one I would like to select, since the peak (`|`) is upstream from that tss. (I am not entirely sure if I am being clear).

**Comment by Maarten-vd-Sande** [comment]
One thing I could do is do it iteratively and filter tss on their orientation and location and then do nearest. However (I havent tested this), I think the performance hit would be great, and ideally I would solve this "vectorized".

**Comment by endrebak** [comment]
You can set a strand on peaks 

```
peaks.Strand = "+"
```

and then use upstream (potentially with `overlap=False`) on individual strands in the tss, but your problem might be more involved?

I will need to think about this.

**Comment by endrebak** [comment]
Do you know if any of the flags in `bedtools closest` could be used to achieve this behavior? Then it would be easy for me to understand and copy it 👍

**Comment by Maarten-vd-Sande** [comment]
I do not see any bedtools closest flag that does what I want.

![image](https://user-images.githubusercontent.com/15323399/91864856-0b1b0080-ec71-11ea-8031-a991e5ca97d0.png)

Some extra explanation: here we have 1 peak (the black vertical bar) and it has no direction, and three genes (arrows). The genes have an orientation (the direction of the arrow), and a tss (yellow diamond). Two genes have a big red cross through them, because the peak can NEVER be upstream of the tss. The remaining gene thus is the closest.

I can do it iteratively, no problem! I was just curious if a "better" way exists, but it is not worth our time :)

Thanks!!

**Comment by endrebak** [comment]
Thanks! Show me an iterative solution (it will likely be slow) and I might be able to vectorize it :)

**Comment by endrebak** [comment]
```
>+++++>   |  <-----<    >++++>
gene 1       gene 2     gene 3

<-----<
gene 4
```

Here gene 4 is the closest one, right?

I think we will find a good solution. I just do not want to rush to implement something before I completely understand.

**Comment by Maarten-vd-Sande** [comment]
Yes gene 4 is the closest

**Comment by Maarten-vd-Sande** [comment]
Like this for the four genes example we just made:

```
peak = {"Chromosome": [1], 
         "Start": [15], 
         "End": [16]}

tss = {"Chromosome": [1, 1, 1, 1], 
       "Start": [0, 12, 30, 10], 
       "End": [1, 13, 31, 11],
       "Strand": ["+", "+", "+", "-"]}

tss = pyranges.from_dict(tss)
peak = pyranges.from_dict(peak)

start = int(peak.Start)
comp_a = peak.nearest(tss[(tss.Start > start) & (tss.Strand == "+")])
comp_b = peak.nearest(tss[(tss.Start < start) & (tss.Strand == "-")])

# take the smaller one
...
```

This could then be placed in a for loop for each peak.

**Comment by endrebak** [comment]
This is just the beginning of an idea I need to sleep on.

I pretend each peak is represented twice, once with each strand. Then I do and upstream search for `peak["+"]` and `tss["+"]`, `peak["-"]` and `tss["-"]`. Then I choose the one with the shortest distance for each of the peak +/- pairs (they have the same ID).

```
import pyranges as pr
import numpy as np

tss = pr.from_string("""Chromosome Start End Strand
1 5 6 +
1 5 6 -
1 10 11 +
1 10 11 -""")
peaks = pr.from_string("""Chromosome Start End
1 0 1
1 7 8
1 12 13""")

peaks.ID = np.arange(len(peaks))
p = pr.concat([peaks, peaks]).sort()
p.Strand = np.tile(["+", "-"], 3)

pminus = p["-"].nearest(tss["-"], how="upstream")
pplus = p["+"].nearest(tss["+"], how="upstream")

df = pr.concat([pplus, pminus]).df
nearest = df.reindex(df.groupby("ID").Distance.min().index)
```

Thanks for the interesting question btw 👍

**Comment by Maarten-vd-Sande** [comment]
But now each tss has a direction both ways?

**Comment by endrebak** [comment]
No, the peaks are given both directions, no strands are added to the TSSes. But the last line chooses the peak with the smallest distance.

```
import pyranges
peak = {"Chromosome": [1],
         "Start": [15],
         "End": [16]}

tss = {"Chromosome": [1, 1, 1, 1],
       "Start": [0, 12, 30, 10],
       "End": [1, 13, 31, 11],
       "Strand": ["+", "+", "+", "-"]}

tss = pyranges.from_dict(tss)
peaks = pyranges.from_dict(peak)
import numpy as np
peaks.ID = np.arange(len(peaks))
p = pr.concat([peaks, peaks]).sort()
p.Strand = np.tile(["+", "-"], int(len(p)/2))
pminus = p["-"].nearest(tss["-"], how="upstream")
pplus = p["+"].nearest(tss["+"], how="upstream")
df = pr.concat([pplus, pminus]).df
nearest = df.reindex(df.groupby("ID").Distance.min().index)
#   Chromosome  Start  End  ID Strand  Start_b  End_b Strand_b  Distance
# ID
# 0           1     15   16   0      +       12     13        +         3
```

**Comment by Maarten-vd-Sande** [comment]
Unless I am confusing the + and -, this is incorrect? 

Position 15-16 is not upstream from 12-13 as a +

**Comment by endrebak** [comment]
I made two mistakes (`upstream` not `downstream`, and `min().index`, not `idxmin`).

I hope the below code does what you expect 👍 

```
import pyranges as pr
import numpy as np

import pyranges
peak = {"Chromosome": [1],
         "Start": [15],
         "End": [16]}

tss = {"Chromosome": [1, 1, 1, 1],
       "Start": [0, 12, 30, 10],
       "End": [1, 13, 31, 11],
       "Strand": ["+", "+", "+", "-"]}

tss = pyranges.from_dict(tss)
peaks = pyranges.from_dict(peak)

def unstranded_upstream(peaks, tss):
    peaks = peaks.copy()
    peaks.ID = np.arange(len(peaks))
    p = pr.concat([peaks, peaks]).sort()
    p.Strand = np.tile(["+", "-"], int(len(p)/2))
    pminus = p["-"].nearest(tss["-"], how="downstream")
    pplus = p["+"].nearest(tss["+"], how="downstream")
    df = pr.concat([pplus, pminus]).df
    # print(df)
    ix = df.groupby("ID").Distance.idxmin()
    nearest = df.reindex(ix)
    return pr.PyRanges(nearest)

print(unstranded_upstream(peaks, tss))
# +--------------+-----------+-----------+-----------+--------------+-----------+-----------+--------------+------------+
# |   Chromosome |     Start |       End |        ID | Strand       |   Start_b |     End_b | Strand_b     |   Distance |
# |   (category) |   (int32) |   (int32) |   (int64) | (category)   |   (int32) |   (int32) | (category)   |    (int64) |
# |--------------+-----------+-----------+-----------+--------------+-----------+-----------+--------------+------------|
# |            1 |        15 |        16 |         0 | -            |        10 |        11 | -            |          5 |
# +--------------+-----------+-----------+-----------+--------------+-----------+-----------+--------------+------------+

tss = pr.from_string("""Chromosome Start End Strand
1 5 6 +
1 5 6 -
1 10 11 +
1 10 11 -
1 13 14 +
1 13 14 -""")
peaks = pr.from_string("""Chromosome Start End
1 0 1
1 7 8
1 12 13""")

print(unstranded_upstream(peaks, tss))
# +--------------+-----------+-----------+-----------+--------------+-------------+-------------+--------------+------------+
# |   Chromosome |     Start |       End |        ID | Strand       |     Start_b |       End_b | Strand_b     |   Distance |
# |   (category) |   (int32) |   (int32) |   (int64) | (category)   |   (float64) |   (float64) | (category)   |    (int64) |
# |--------------+-----------+-----------+-----------+--------------+-------------+-------------+--------------+------------|
# |            1 |         0 |         1 |         0 | +            |           5 |           6 | +            |          5 |
# |            1 |        12 |        13 |         2 | +            |          13 |          14 | +            |          1 |
# |            1 |         7 |         8 |         1 | -            |           5 |           6 | -            |          2 |
# +--------------+-----------+-----------+-----------+--------------+-------------+-------------+--------------+------------+
# Stranded PyRanges object has 3 rows and 9 columns from 1 chromosomes.
# For printing, the PyRanges was sorted on Chromosome and Strand.

```

**Comment by Maarten-vd-Sande** [comment]
Awesome! This indeed does what I was looking for. Thanks a lot for your help (and pyrange in general)!!!

:+1: :rocket: :1st_place_medal:

**Comment by endrebak** [comment]
Cool!

It is great to have these problems solved and googleable. This might be a problem other people have too so I should start collecting recipes. This might also be worthy of inclusion in pyranges at some point.
