### ISSUE TITLE
Bedtools coverage 

### ISSUE THREAD

**Issue by tbrittoborges** [biocore-ntnu/pyranges#16]
Is there a function to calculate the coverage or fraction of intersect of two or more pyranges?
Similar to https://bedtools.readthedocs.io/en/latest/content/tools/coverage.html

**Comment by endrebak** [comment]
https://biocore-ntnu.github.io/pyranges/statistics-similarity-between-pyranges.html

and

https://biocore-ntnu.github.io/pyranges/statistics-spatial-correlations-between-pyranges.html

Will answer more when I’m back in front of a computer. (These stats-methods
are not as rigorously tested yet, because my method of testing is comparing
my result against the result of running bedtools on the same random data
and I found bugs in bedtools.)

Endre

**Comment by endrebak** [comment]
There is currently no equivalent to the coverage-function (pr.coverage gives an RLE). I do not think it should be hard to write though given the tools that currently exist in PyRanges though. I will add it to my TODO-list, but I have a lot I should finish before I add it though :)

**Comment by tbrittoborges** [comment]
It's feasible to do it with a mix of pyranges.intersect + some computations with the pands.DataFrames. I was just askig because we want to replace some of ours pybedtools calls, and a robust coverage function would be necessary.

**Comment by endrebak** [comment]
I have added coverage to 0.0.48. Thanks for the request :)

```
import pyranges as pr
exons, cpg = pr.data.exons(), pr.data.cpg()
r = cpg.coverage(exons)
r[r.FractionOverlaps > 0]
+--------------+-----------+-----------+-----------+------------------+----------------------+
| Chromosome   | Start     | End       | CpG       | NumberOverlaps   | FractionOverlaps     |
| (category)   | (int32)   | (int32)   | (int64)   | (int64)          | (float64)            |
|--------------+-----------+-----------+-----------+------------------+----------------------|
| chrX         | 584563    | 585326    | 66        | 1                | 0.32503276539973786  |
| chrX         | 1510501   | 1511838   | 173       | 1                | 0.1854899027673897   |
| chrX         | 1553851   | 1554115   | 20        | 1                | 0.23484848484848486  |
| chrX         | 2846195   | 2847511   | 92        | 1                | 0.1094224924012158   |
| ...          | ...       | ...       | ...       | ...              | ...                  |
| chrY         | 14532115  | 14533600  | 126       | 1                | 0.027609427609427608 |
| chrY         | 15591259  | 15591720  | 33        | 4                | 0.7093275488069414   |
| chrY         | 16941822  | 16942188  | 32        | 1                | 1.0                  |
| chrY         | 26979889  | 26980116  | 21        | 1                | 0.6607929515418502   |
+--------------+-----------+-----------+-----------+------------------+----------------------+
Unstranded PyRanges object has 72 rows and 6 columns from 2 chromosomes.
```
