### ISSUE TITLE
Float values for chromosome start and end

### ISSUE THREAD

**Issue by EvoEpi** [biocore-ntnu/pyranges#166]
Is there a way to have float values for the chromosome start and end positions? E.g.:

chr,start,end
1,100.75,150.25
1,500.00,1000.987654321

**Comment by endrebak** [comment]
No, but I have a version of the ncls that supports floats: https://github.com/biocore-ntnu/ncls

**Comment by EvoEpi** [comment]
I think I can work with the code you have in `examples`. Thank you!

**Comment by endrebak** [comment]
Feel free to open an issue in the NCLS repo if you have any questions :)
