### ISSUE TITLE
Subsetting exception

### ISSUE THREAD

**Issue by caitlin-f** [biocore-ntnu/pyranges#17]
Just following the example for subsetting from the documentation but I get the following exception:
```
>>> print(cpg[cpg.CpG > 50])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyranges/pyranges.py", line 101, in __getitem__
    return _getitem(self, val)
  File "pyranges/methods/getitem.py", line 20, in _getitem
    raise Exception("Not valid subsetter: {}".format(str(val)))
Exception: Not valid subsetter: 0        True
1        True
2        True
3        True
4       False
        ...
1072     True
1073    False
1074    False
1075    False
1076    False
Name: CpG, Length: 1077, dtype: bool
```

**Comment by endrebak** [comment]
Thanks for reporting! Are you on 0.0.46? That is where boolean indexing was introduced :)

```python -c 'import pyranges; print(pyranges.__version__)'```

**Comment by caitlin-f** [comment]
Ah okay, no I'm on 0.0.45 (from bioconda)

**Comment by endrebak** [comment]
Bioconda is lagging behind. It is due to PRs having to be reviewed now. pip install should do the trick.

**Comment by endrebak** [comment]
You can still do gr.subset(lambda df: df.CpG > 50), which is slightly faster, but more inconvenient.

**Comment by endrebak** [comment]
Now 0.0.48 is out on bioconda. Please feel free to reopen if you have further issues :)
