### ISSUE TITLE
ValueError with max_disjoint()

### ISSUE THREAD

**Issue by callum-b** [biocore-ntnu/pyranges#174]
I tried to use `max_disjoint()` after resizing my pyranges, but it throws a value error.

`hotspots.Start = ((hotspots.Start + hotspots.End)/2).astype(np.int32) # int is 64 bit
hotspots.End = hotspots.Start + 1
clusters = hotspots.max_disjoint(slack=5000)`

> ValueError                                Traceback (most recent call last)
<ipython-input-4-ecb6b9b87d51> in <module>
      2 hotspots.Start = ((hotspots.Start + hotspots.End)/2).astype(np.int32) # int is 64 bit
      3 hotspots.End = hotspots.Start + 1
----> 4 clusters = hotspots.max_disjoint(slack=5000)
      5 clusters
~/anaconda3/lib/python3.8/site-packages/pyranges/pyranges.py in max_disjoint(self, strand, slack, **kwargs)
   2718 
   2719         from pyranges.methods.max_disjoint import _max_disjoint
-> 2720         df = pyrange_apply_single(_max_disjoint, self, **kwargs)
   2721 
   2722         return pr.PyRanges(df)
~/anaconda3/lib/python3.8/site-packages/pyranges/multithreaded.py in pyrange_apply_single(function, self, **kwargs)
    358 
    359             df = make_unary_sparse(kwargs, df)
--> 360             result = call_f_single(function, nparams, df, **kwargs)
    361             results.append(result)
    362             keys.append(c)
~/anaconda3/lib/python3.8/site-packages/pyranges/multithreaded.py in call_f_single(f, nparams, df, **kwargs)
     28 
     29     if nparams == 2:
---> 30         return f.remote(df, **kwargs)
     31     else:
     32         return f.remote(df)
~/anaconda3/lib/python3.8/site-packages/pyranges/methods/max_disjoint.py in _max_disjoint(df, **kwargs)
     13     cdf = df.sort_values("End")
     14 
---> 15     idx = max_disjoint(cdf.index.values, cdf.Start.values, cdf.End.values, slack)
     16 
     17     return cdf.reindex(idx)
~/anaconda3/lib/python3.8/site-packages/sorted_nearest/src/max_disjoint_intervals.pyx in sorted_nearest.src.max_disjoint_intervals.max_disjoint()
ValueError: Buffer dtype mismatch, expected 'const int32_t' but got 'long long'

**Comment by endrebak** [comment]
Ill fix it tomorrow! Do not have access to a computer right now
:)

**Comment by endrebak** [comment]
The error is not in max_disjoint, but in the fact that after your modifications, the pyranges has a start column with in32, but an ends column with int64.

```
hotspots.Start = ((hotspots.Start + hotspots.End)/2).astype(np.int32) 
hotspots.End = (hotspots.Start + 1).astype(int32)
```

This is surprising behavior from pyranges, do not know how to fix it atm. Will think.

**Comment by endrebak** [comment]
In 0.0.94 a warning will be printed if `Start.dtype != End.dtype`
