### ISSUE TITLE
join/merge function

### ISSUE THREAD

**Issue by kridsadakorn** [biocore-ntnu/pyranges#18]
I want to merge/join two Pyranges objects, let say obj1 and obj2. And I still want to trackback the indices of obj1 and obj2. I tried to use 'join' but the function returns with a completely new object which I couldn't trackback the indices of obj1 and obj2 anymore. I imagine it will be similar to the merge function in R. Any suggestion? Or the join function should be improved?

**Comment by endrebak** [comment]
There are no indexes in Pyranges. You can give each pyrange an ID before joining.

```
gr1.index1 = list(range(len(gr1)))
gr2.index2 = list(range(len(gr2)))
gr1.join(gr2)
```

Then you know which is where.

What in particular are you trying to do? There is likely an easy way to do it :)

**Comment by endrebak** [comment]
Thanks for reporting btw :)

**Comment by kridsadakorn** [comment]
I want to know the information of my reads; which genes/TF/enchancers/etc. are close by based on given extended range eg. +/- 1000 bps.
So I'm trying to map the reads to an annotation file and some reads can be mapped to multiple genes.
The result from join function reports the extended position according to the given range (+/- 1000 bps). But I'm more interested to know about the information of my reads. Since the result of join function doesn't report the original indices of both tables/dataframes (to be say); so I couldn't directly link to the reads in the previous table/dataframe.

**Comment by endrebak** [comment]
Okay. But all the information in A and B is kept when you join two pyranges A and B. So if A is your reads, the read info is in the first columns of the new pyranges, while the annotation info from B is in the last columns.

When you give A an ID like in my example above, it should be possible to find the original reads I hope :) If not I would appreciate it if you could try to show me what your start data looks like and what you want to end up with.

**Comment by kridsadakorn** [comment]
> Okay. But all the information in A and B is kept when you join two pyranges A and B. So if A is your reads, the read info is in the first columns of the new pyranges, while the annotation info from B is in the last columns.
> 
> When you give A an ID like in my example above, it should be possible to find the original reads I hope :) If not I would appreciate it if you could try to show me what your start data looks like and what you want to end up with.

Thank you, your idea above works.

**Comment by endrebak** [comment]
Cool. If there is something I can do to make it easier, please tell me. Closing this, but feel free to reopen or ask other questions :)
