### ISSUE TITLE
File not closed in readers.py

### ISSUE THREAD

**Issue by Rohan-cod** [biocore-ntnu/pyranges#180]
In [readers.py](https://github.com/biocore-ntnu/pyranges/blob/master/pyranges/readers.py), we open the file 'f' but never close it.
![Screenshot 2021-04-10 at 9 43 50 PM](https://user-images.githubusercontent.com/47586886/114276849-1bd0f780-9a46-11eb-9f92-b7be497a1b9b.jpg)
Can we assign `open(f)` to a variable and then close it after we create first_start?

**Comment by endrebak** [comment]
As there is no reference to the file handle anywhere it will be garbage collected and closed. But I see it gives you bothersome warnings so I will fix it :)

**Comment by Rohan-cod** [comment]
> I will fix it :)

Thanks a lot, @endrebak. :)

**Comment by Rohan-cod** [comment]
Fixed via #181 by @endrebak.
