### ISSUE TITLE
Merge and groupBy ?

### ISSUE THREAD

**Issue by gouthamatla** [biocore-ntnu/pyranges#185]
Hi All,

Bedtools has a very useful feature to groupBy when merging a bed file. 

E.g:

```
% cat A.bed 
chr1	100	200	a1	1	+
chr1	180	250	a2	2	+
chr1	250	500	a3	3	-
chr1	501	1000	a4	4	+

```

```
% mergeBed -i A.bed -c 5 -o min
chr1	100	500	1
chr1	501	1000	4

```

```
% mergeBed -i A.bed -c 5 -o max 
chr1	100	500	3
chr1	501	1000	4

```

Is it possible to do that in pyranges or pyranges.merge() ? This will help to keep some meta information when merging peaks, like to keep a median strength of the peaks that were merged.

Thanks,
Goutham A

**Comment by endrebak** [comment]
Try `df = gr.cluster().df; df.groupby("Cluster").apply(max)`

I saw no need to implement groupby as pandas has that functionality. The grammar might be wrong as I'm writing this on my mobile.

**Comment by gouthamatla** [comment]
Thanks. I will try it.

**Comment by endrebak** [comment]
Feel free to ping me here if you need help with the groupbys. I love
solving genomics-problems :)
