### ISSUE TITLE
join: ValueError: Buffer dtype mismatch, expected 'const long' but got Python object

### ISSUE THREAD

**Issue by kridsadakorn** [biocore-ntnu/pyranges#19]
my_data contains the reads I want to map to genes
my_annotation contains the gene information

When I do this:
```
my_annotation.join(my_data)
```
It is OK.

But when I do this:

```
my_data.join(my_annotation)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.local/lib/python3.6/site-packages/pyranges/pyranges.py", line 230, in join
    dfs = pyrange_apply(_write_both, self, other, **kwargs)
  File "/.local/lib/python3.6/site-packages/pyranges/multithreaded.py", line 271, in pyrange_apply
    result = call_f(function, nparams, df, odf, kwargs)
  File "/.local/lib/python3.6/site-packages/pyranges/multithreaded.py", line 22, in call_f
    return f.remote(df, odf, kwargs)
  File "/.local/lib/python3.6/site-packages/pyranges/methods/join.py", line 45, in _write_both
    scdf, ocdf = _both_dfs(scdf, ocdf, how=how)
  File "/.local/lib/python3.6/site-packages/pyranges/methods/join.py", line 18, in _both_dfs
    starts, ends, indexes)
  File "ncls/src/ncls32.pyx", line 76, in ncls.src.ncls32.NCLS32.all_overlaps_both
ValueError: Buffer dtype mismatch, expected 'const long' but got Python object
```

Here is how my_data looks like

```
+--------------+-----------+-----------+-----------+
| Chromosome   | Start     | End       | Index     |
| (category)   | (int32)   | (int32)   | (int64)   |
|--------------+-----------+-----------+-----------|
| 1            | 3003842   | 3014343   | 0         |
| 1            | 3025329   | 3035830   | 1         |
| 1            | 3030643   | 3041144   | 2         |
| 1            | 3057723   | 3068243   | 3         |
```
Here is how my_annotation looks like

```
+--------------+------------+-------------+-----------+-----------+--------------+-------+
| Chromosome   | source     | gene_type   | Start     | End       | Strand       | ...   |
| (category)   | (object)   | (object)    | (int32)   | (int32)   | (category)   | ...   |
|--------------+------------+-------------+-----------+-----------+--------------+-------|
| 1            | havana     | gene        | 3073253   | 3074322   | +            | ...   |
| 1            | havana     | transcript  | 3073253   | 3074322   | +            | ...   |
| 1            | havana     | exon        | 3073253   | 3074322   | +            | ...   |
| 1            | ensembl    | gene        | 3102016   | 3102125   | +            | ...   |
```

Do you have any idea about this error?

**Comment by endrebak** [comment]
Does the problem persist if you do `pip install -U pyranges` or `conda install -c bioconda pyranges`?

If it does, what is the output of 

```
import ncls
ncls.__version__
import pyranges
pyranges.__version__
```
?

Thanks.

**Comment by endrebak** [comment]
I will try to reproduce tomorrow if upgrading does not work for you. Thanks for bothering to report :)

**Comment by kridsadakorn** [comment]
Thank you for a quick reply I will test tomorrow.

I also would like to ask another question. When one read can be mapped to multiple genes, we will get multi-rows of the result from "join". Are there any simple way in pyranges; without looping; to get a set of unique rows and combined information instead, for example, "gene1, gene2, gene3", and reads which can't be mapped to any gene, it will be None or NA.

**Comment by endrebak** [comment]
NP. I will check issues once a day at least, except in weekends :)

1) No, having multiple entries in one cell is considered untidy data. See https://vita.had.co.nz/papers/tidy-data.pdf

Of course, sometimes you want untidy data. Since you can use pandas/python to process the data in pyranges, multiple entries per row should not be too hard to get. I will try to create an example later, when I am in front of a computer :)

2) Getting entries in A that were not in B sounds like useful functionality. I will try to think about how to best implement it :)

**Comment by kridsadakorn** [comment]
> Does the problem persist if you do `pip install -U pyranges` or `conda install -c bioconda pyranges`?
> 
> If it does, what is the output of
> 
> ```
> import ncls
> ncls.__version__
> import pyranges
> pyranges.__version__
> ```
> 
> ?
> 
> Thanks.

Still have a problem
Here it is:

> >>> import ncls

> >>> ncls.__version__

> '0.0.43'

> >>> import pyranges

> >>> pyranges.__version__

> '0.0.51'

**Comment by kridsadakorn** [comment]
> NP. I will check issues once a day at least, except in weekends :)
> 
> 1. No, having multiple entries in one cell is considered untidy data. See https://vita.had.co.nz/papers/tidy-data.pdf
> 
> Of course, sometimes you want untidy data. Since you can use pandas/python to process the data in pyranges, multiple entries per row should not be too hard to get. I will try to create an example later, when I am in front of a computer :)
> 
> 1. Getting entries in A that were not in B sounds like useful functionality. I will try to think about how to best implement it :)

In general, A and B may have different sizes. A may have more rows than B, or B may have more rows than A. A can be partially mapped with B, and vice versa. I think it would be good if there is an option to select whether we want only mapped data or full data with NA or None. For example:
- When A > B, we can select to get only rows in A that can be mapped to B, or all rows in A with NA/None for rows that cannot be mapped to B.
- Also similar for the case "when A < B"

Currently what the "join" function returns for the rows that cannot be mapped? Are these rows thrown away?

**Comment by endrebak** [comment]
I cannot reproduce with the test data in pyranges. Can you please post every step of your analysis/the analysis script?

And what is the output of 

```
my_annotation.dfs.keys()
my_data.dfs.keys()
```

please?

The error says that the datatype of either the starts, ends or indexes is not int32/int64, but a Python object. Weird.

**Comment by kridsadakorn** [comment]
> I cannot reproduce with the test data in pyranges. Can you please post every step of your analysis/the analysis script?
> 
> And what is the output of
> 
> ```
> my_annotation.dfs.keys()
> my_data.dfs.keys()
> ```
> 
> please?
> 
> The error says that the datatype of either the starts, ends or indexes is not int32/int64, but a Python object. Weird.

>>> my_data.dfs.keys()
dict_keys(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', 'X', 'Y'])


>>> my_annotation.dfs.keys()
dict_keys([('1', '+'), ('1', '-'), ('10', '+'), ('10', '-'), ('11', '+'), ('11', '-'), ('12', '+'), ('12', '-'), ('13', '+'), ('13', '-'), ('14', '+'), ('14', '-'), ('15', '+'), ('15', '-'), ('16', '+'), ('16', '-'), ('17', '+'), ('17', '-'), ('18', '+'), ('18', '-'), ('19', '+'), ('19', '-'), ('2', '+'), ('2', '-'), ('3', '+'), ('3', '-'), ('4', '+'), ('4', '-'), ('5', '+'), ('5', '-'), ('6', '+'), ('6', '-'), ('7', '+'), ('7', '-'), ('8', '+'), ('8', '-'), ('9', '+'), ('9', '-'), ('GL456210.1', '+'), ('GL456210.1', '-'), ('GL456211.1', '+'), ('GL456211.1', '-'), ('GL456212.1', '-'), ('GL456216.1', '+'), ('GL456216.1', '-'), ('GL456219.1', '-'), ('GL456221.1', '+'), ('GL456221.1', '-'), ('GL456233.1', '+'), ('GL456233.1', '-'), ('GL456239.1', '+'), ('GL456350.1', '-'), ('GL456354.1', '+'), ('GL456354.1', '-'), ('GL456372.1', '-'), ('GL456381.1', '-'), ('GL456385.1', '+'), ('JH584292.1', '+'), ('JH584293.1', '+'), ('JH584293.1', '-'), ('JH584294.1', '+'), ('JH584294.1', '-'), ('JH584295.1', '-'), ('JH584296.1', '-'), ('JH584297.1', '+'), ('JH584297.1', '-'), ('JH584298.1', '+'), ('JH584298.1', '-'), ('JH584299.1', '+'), ('JH584299.1', '-'), ('JH584303.1', '+'), ('JH584304.1', '-'), ('MT', '+'), ('MT', '-'), ('X', '+'), ('X', '-'), ('Y', '+'), ('Y', '-')])

>>> my_annotation
+--------------+------------+-------------+-----------+-----------+--------------+-------+
| Chromosome   | source     | gene_type   | Start     | End       | Strand       | ...   |
| (category)   | (object)   | (object)    | (int32)   | (int32)   | (category)   | ...   |
|--------------+------------+-------------+-----------+-----------+--------------+-------|
| 1            | havana     | gene        | 3073253   | 3074322   | +            | ...   |
| 1            | havana     | transcript  | 3073253   | 3074322   | +            | ...   |
| 1            | havana     | exon        | 3073253   | 3074322   | +            | ...   |
| 1            | ensembl    | gene        | 3102016   | 3102125   | +            | ...   |
| ...          | ...        | ...         | ...       | ...       | ...          | ...   |

This is interesting the keys of the annotation is chromosome plus Strand.

**Comment by endrebak** [comment]
The join function only returns those entries in A with an overlap in B. This is actually because of how pandas handles nan (which there would be alot of in the B columns if you kept all rows from A):

```
import pyranges as pr
g = pr.data.f1()
df = g.df
df2 = df.append({k: v for k, v in zip(df.columns, ["chr1", 9, 10, "hi", pr.np.nan,  "+"])}, ignore_index=True)
g2 = pr.PyRanges(df2)
g2
# +--------------+------------+------------+------------+------------+------------+
# | Chromosome   |      Start |        End | Name       |      Score | Strand     |
# | (object)     |   (object) |   (object) | (object)   |   (object) | (object)   |
# |--------------+------------+------------+------------+------------+------------|
# | chr1         |          3 |          6 | interval1  |          0 | +          |
# | chr1         |          8 |          9 | interval3  |          0 | +          |
# | chr1         |          9 |         10 | hi         |        nan | +          |
# | chr1         |          5 |          7 | interval2  |          0 | -          |
# +--------------+------------+------------+------------+------------+------------+
# Stranded PyRanges object has 4 rows and 6 columns from 1 chromosomes.
```

Here you see that the Score column is demoted from integer to object since the
dataframe is missing data.

Would a function A.no_overlap(B) which told you which entries in A has no overlap in B be helpful for you?

**Comment by endrebak** [comment]
Do you have the opportunity to share the data you are using with me? On google drive for example? You can send the link by e-mail.

PyRanges should handle stranded and unstranded data together :) It just ignores the strand when one of them is missing :)

**Comment by endrebak** [comment]
Also, I would love to see whole analysis script. Will look at this more later tonight :)

**Comment by endrebak** [comment]
Keeping this open in case others experience the same thing :)

**Comment by kridsadakorn** [comment]
Hi, I will cut some parts of the data, and the annotation for you to test. Because they are quite big.

**Comment by endrebak** [comment]
Have not been able to reproduce. I am guessing the dfs were modified in-place in some way :)
