### ISSUE TITLE
Finding difference between bed files

### ISSUE THREAD

**Issue by hkmztrk** [biocore-ntnu/pyranges#190]
Hello, I have two bed files and I want to remove the overlapping  intervals from the first one. 

A.bed
| chrom        | start             | end
| ----------- | ----------- | ----------- |
| chr1           | 5       |  12  |
| chr1           | 48        | 79  |

B.bed
| chrom        | start             | end
| ----------- | ----------- | ----------- |
| chr1           | 8      |  19      |
| chr1           | 98        | 109  |

diff.bed
| chrom        | start             | end
| ----------- | ----------- | ----------- |
| chr1           | 48        | 79  |

What would be the best way to get diffbed? 

Thanks!

**Comment by endrebak** [comment]
Does `gr.subtract(gr2)` do what you want?

**Comment by endrebak** [comment]
```
In [8]: gr = pr.from_string("""
   ...: Chromosome Start End
   ...: chr1^I5^I12
   ...: chr1^I48^I79""")

In [9]: gr2 = pr.from_string("""
   ...: Chromosome Start End
   ...: chr1^I8^I19
   ...: chr1^I98^I109""")

In [10]: gr.overlap(gr2, invert=True)
Out[10]:
+--------------+-----------+-----------+
| Chromosome   |     Start |       End |
| (category)   |   (int32) |   (int32) |
|--------------+-----------+-----------|
| chr1         |        48 |        79 |
+--------------+-----------+-----------+
Unstranded PyRanges object has 1 rows and 3 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome.

In [11]: gr.subtract(gr2)
Out[11]:
+--------------+-----------+-----------+
| Chromosome   |     Start |       End |
| (category)   |   (int32) |   (int32) |
|--------------+-----------+-----------|
| chr1         |         5 |         8 |
| chr1         |        48 |        79 |
+--------------+-----------+-----------+
Unstranded PyRanges object has 2 rows and 3 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
```

**Comment by endrebak** [comment]
So option 1 :)

**Comment by hkmztrk** [comment]
Thanks @endrebak! Yes, `subtract` didn't work. Thanks for pointing out the `invert` argument - I couldn't find an explanation in the documentation. In the end I just used data frames to do that, but this solution makes it simpler.
