### ISSUE TITLE
read_gtf throws an error

### ISSUE THREAD

**Issue by Serfentum** [biocore-ntnu/pyranges#193]
Hi! Thank you for the library, seems like it really cool)

But unfortunately it doesn't work in my case. I've created separate environment with python 3.7 in conda and install pyranges using   default command from README. Everything went ok, but that sample throws an error

```python
import pyranges


gtf_path = 'Chinese_treeshrew_TS2.0.annotation/Chinese_treeshrew_TS2.0.gtf'
gtf = pyranges.read_gtf(gtf_path)
```
And here is an error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/a.ilin/anaconda3/envs/genomic/lib/python3.7/site-packages/pyranges/readers.py", line 301, in read_gtf
    gr = read_gtf_full(f, as_df, nrows, _skiprows, duplicate_attr)
  File "/home/a.ilin/anaconda3/envs/genomic/lib/python3.7/site-packages/pyranges/readers.py", line 331, in read_gtf_full
    extra = _to_rows(df.Attribute)
  File "/home/a.ilin/anaconda3/envs/genomic/lib/python3.7/site-packages/pyranges/readers.py", line 358, in to_rows
    for kv in l[:-1].split("; ")]})
  File "/home/a.ilin/anaconda3/envs/genomic/lib/python3.7/site-packages/pyranges/readers.py", line 356, in <dictcomp>
    for k, v in [kv.replace('"', '').split(None, 1)
```

Perhaps something wrong with my gtf file? Here is a link to the archive with it
http://www.treeshrewdb.org/data/Chinese_treeshrew_TS2.0.annotation.zip

Thank you very much!

Best,
Alexander

P.S.: Call for charity in README is awesome

**Comment by endrebak** [comment]
Would you be able to share the file with me and I’ll find out why it fails :) Thanks for all the kind words :)

**Comment by endrebak** [comment]
I now see you posted the link. Will try today if my daughter falls asleep early enough. Otherwise I’ll do it Monday

**Comment by endrebak** [comment]
Your last column is malformed. Look up [this page](http://m.ensembl.org/info/website/upload/gff.html) for how it is supposed to look :)

I am adding a boolean argument `full` to `read_gtf`/`read_gff3` so that you can read your file without the last column.

**Comment by endrebak** [comment]
See this page: http://m.ensembl.org/info/website/upload/gff.html :)

**Comment by Serfentum** [comment]
Hi!) 
Thank you very much, I've requested for the proper one, and now it works
Have a nice day)

**Comment by endrebak** [comment]
I am happy to hear that :)
