### ISSUE TITLE
Bug in read_gtf(annotation="ensembl")

### ISSUE THREAD

**Issue by ricchasethi** [biocore-ntnu/pyranges#197]
Hi,

I am using pyranges and there seems to be a bug in read_gtf(annotation="ensembl") function. After the gtf file is read then the Start coordinate is 1bp less than the one in gtf file. For example:
gtf file row:

```
1       havana  gene    11869   14409   .       +       .       gene_id "ENSG00000223972"; gene_version "5"; gene_name "DDX11L1"; gene_source "havana"; gene_biotype "transcribed_unprocessed_pseudogene"; havana_gene "OTTHUMG00000000961"; havana_gene_version "2";
```

file after 
```
pr.read_gtf("test.gtf", annotation="ensembl"):
+--------------+------------+--------------+-----------+-----------+------------+--------------+------------+------------+-------+
| Chromosome   | Source     | Feature      | Start     | End       | Score      | Strand       | Frame      | ccds_id    | +21   |
| (category)   | (object)   | (category)   | (int32)   | (int32)   | (object)   | (category)   | (object)   | (object)   | ...   |
|--------------+------------+--------------+-----------+-----------+------------+--------------+------------+------------+-------|
| 1            | havana     | gene         | 11868     | 14409     | .          | +            | .          | nan        | ...   |
```

Q1) Could you please look into it. 

Also, when I add 1 to Start coordinate in the pyranges object using this command:
```
gtfFile.Start = gtfFile.Start + 1
```
then `dtype` of `Start` changes from `int32` to `int64`. This gives me following error down the line:

ValueError: Buffer dtype mismatch, expected 'const int32_t' but got 'long'

Q2) I was wondering is there a way to specify a dtype to a column in pyrange object?

**Comment by endrebak** [comment]
Q1) In different bioinformatics filetypes start/ends mean different things. PyRanges takes care of this so you do not have to. If you try to write it out as a GTF you should see that it writes 11869.

Q2)

```
import numpy as np
gtfFile.Start = (gtfFile.Start + 1).astype(np.int32)
```

**Comment by endrebak** [comment]
Thanks for asking btw :)

**Comment by ricchasethi** [comment]
Thanks for your reply.
Regarding Q1, it is actually confusing to see that start coordinate is 1 bp less while end coordinate remains same. Plus, in a scenario where I need the start coordinate of certain exon, then it is always 1 bp less. Thats why it was bit confusing for me. But thanks for clarification.
