### ISSUE TITLE
What to do about PyRanges too wide to display in terminal?

### ISSUE THREAD

**Issue by endrebak** [biocore-ntnu/pyranges#2]
One thing I have been wondering about is what to do in case the range is too wide to display properly. I guess truncating the columns `Chromosome Strand Start End` to `Position` in the display and only have one column in the displayed output like

```
Position
chr1:100-200:+
```

without changing the underlying data would be an improvement.

But this is something that one should be able to change in the settings.

In case it is still too wide, I guess I will have to remove a few columns and just display `...` instead.

**Comment by vsbuffalo** [comment]
So I was implementing something like pyranges on my own recently (based on interval trees) which was going to be a more advanced version of my [BioRanges library](https://github.com/vsbuffalo/BioRanges/) you mention in the readme, but what you're doing here looks to be further along. I was going to bring up this same issue you have here, but see you did already.

In the new library I was implementing, I had a `head(nentries)` method, which simply used pandas dataframes to pretty print the genomic intervals and associated data. The printing uses up less screen space than tabulate, and would remove this dependency. Might this be an alternative? 

I also have some other methods which I think combine some useful aspects of R's tidyverse with genomic range operations that I can port over to pyranges if you are open to collaboration. Do feel free to email me if it's easier to discuss offline (my email is my github name at Google's mail service).

**Comment by endrebak** [comment]
Hi -- I am interested in collaborating. I will send you an e-mail later today :)

Endre

**Comment by endrebak** [comment]
I actually like tabulate as I find the data much easier to read. In my local version, I have started hiding the rightmost columns as long as they are wider than the screen width. But I was going to add a settings dict which would let you control many aspects of the printing, and indeed let you use only pandas for printing if you so desired.

**Comment by endrebak** [comment]
Mail sent :)
