### ISSUE TITLE
Enable compression of data frames when writing to csv

### ISSUE THREAD

**Issue by cfriedline** [biocore-ntnu/pyranges#20]
Thanks for the great addition to the Python ecosystem!  We are starting to incorporate this into some of our systems, which operate on models built from large amounts of transcript and exon range data. We build these models now with the really nice `interlap` library and drop them to pickles for reuse.

Saving our PyRanges objects to csv files is an excellent replacement for this, but they are kind of large when written (~70MB). It would be great to pass the `compression` kwarg of pandas, like you're currently doing with `sep` and `header` to reduce that size.

**Comment by endrebak** [comment]
I do not use it because pandas seems to autodetect based on extension. Is that good enough for you?

```
ipython
Python 3.7.3 (default, Mar 27 2019, 22:11:17)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.6.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pyranges as pr

In [2]: pr.data.f1().to_csv("hi.txt.gz")
Out[2]:
+--------------+------------+------------+------------+------------+------------+
| Chromosome   |      Start |        End | Name       |      Score | Strand     |
| (object)     |   (object) |   (object) | (object)   |   (object) | (object)   |
|--------------+------------+------------+------------+------------+------------|
| chr1         |          3 |          6 | interval1  |          0 | +          |
| chr1         |          8 |          9 | interval3  |          0 | +          |
| chr1         |          5 |          7 | interval2  |          0 | -          |
+--------------+------------+------------+------------+------------+------------+
Stranded PyRanges object has 3 rows and 6 columns from 1 chromosomes.

Job 2, “ipython” has stopped
biocore-home ~/c/epigenome_roadmap_analyses (master DU=) zcat hi.txt.gz
chr1,3,6,interval1,0,+
chr1,8,9,interval3,0,+
chr1,5,7,interval2,0,-
biocore-home ~/c/epigenome_roadmap_analyses (master DU=) head hi.txt.gz
��J]�hi.txtJ�(2�1�1���+I-*K�1�1���J	[�X�����Dq9���J]�hi.txtJ�(2�1�1���+I-*K�1�1������h�=⏎
```

Thanks for the kind words, btw.

**Comment by endrebak** [comment]
You can also do `gr.df.to_csv()` to get the pandas API. This concatenates the PyRanges first (using the df property) so it is a bit slower.

**Comment by cfriedline** [comment]
You're totally right, I forgot about this "feature" of pandas. In fact, I should probably use it more in my own code...

**Comment by endrebak** [comment]
I am adding the compression argument to `to_csv`, `to_gtf`, `to_bed` in the next version though. "infer" is the default. :) 

Explicit is better than implicit (but file endings are pretty explicit even though they are only part of the name in unixy systems). 

Also interlap seems cool - great speed for a pure Python library!
