### ISSUE TITLE
`five_end` incorrect output

### ISSUE THREAD

**Issue by alecchap** [biocore-ntnu/pyranges#208]
It seems that `five_end()` is returning the interval start regardless of the strand.  `three_end()` seems to be better, except that the intervals have the same start and end rather than differing by one as the documentation suggests.  I'm using version 0.0.98.

    >>> gr = pr.from_dict({'Chromosome': ['chr1', 'chr1'], 'Start': [3, 5], 'End': [9, 7], 'Strand': ["+", "-"]})
    >>> gr
    +--------------+-----------+-----------+--------------+
    | Chromosome   |     Start |       End | Strand       |
    | (category)   |   (int32) |   (int32) | (category)   |
    |--------------+-----------+-----------+--------------|
    | chr1         |         3 |         9 | +            |
    | chr1         |         5 |         7 | -            |
    +--------------+-----------+-----------+--------------+
    Stranded PyRanges object has 2 rows and 4 columns from 1 chromosomes.
    For printing, the PyRanges was sorted on Chromosome and Strand.
    >>> gr.five_end()
    +--------------+-----------+-----------+--------------+
    | Chromosome   |     Start |       End | Strand       |
    | (category)   |   (int32) |   (int32) | (category)   |
    |--------------+-----------+-----------+--------------|
    | chr1         |         3 |         3 | +            |
    | chr1         |         5 |         5 | -            |
    +--------------+-----------+-----------+--------------+
    Stranded PyRanges object has 2 rows and 4 columns from 1 chromosomes.
    For printing, the PyRanges was sorted on Chromosome and Strand.
    >>> gr.three_end()
    +--------------+-----------+-----------+--------------+
    | Chromosome   |     Start |       End | Strand       |
    | (category)   |   (int32) |   (int32) | (category)   |
    |--------------+-----------+-----------+--------------|
    | chr1         |         9 |         9 | +            |
    | chr1         |         5 |         5 | -            |
    +--------------+-----------+-----------+--------------+
    Stranded PyRanges object has 2 rows and 4 columns from 1 chromosomes.
    For printing, the PyRanges was sorted on Chromosome and Strand.

**Comment by endrebak** [comment]
I think this was recently fixed. Do you mind updating and trying again? If not I’ll fix it tomorrow.

thanks for reporting. Appreciate it!

**Comment by endrebak** [comment]
I broke it, did not fix it. 9-9 is a zero-length interval. Will fix now.

**Comment by endrebak** [comment]
I've fixed it now, but need to run all tests before I push :)

Thanks! So embarrassing.

**Comment by endrebak** [comment]
Should be fixed in 0.0.104 which is out now: https://github.com/biocore-ntnu/pyranges/pull/210/files

**Comment by alecchap** [comment]
Thanks for the quick fix, and for the library more generally.  It's been quite useful for me!
