### ISSUE TITLE
add columns from overlap object

### ISSUE THREAD

**Issue by SanderEST** [biocore-ntnu/pyranges#21]
Is there a possibility to add columns from the pyranges which was used for overlapping. What I mean is that let's say one uses a subset of gtf file as regions of interest, but after overlapping wants to also annotate with other columns like gene name from gtf file. 

It could be an option like this:
`gr.overlap(gr_gtf, addcols = True)`
The output would have all rows from gr that overlap with gtf, but in addition also all columns from gtf object for each overlap.

**Comment by endrebak** [comment]
join does this if I understand you correctly. Thanks for trying PyRanges btw, it makes me happy :)

`gr.join(gr_gtf)`

**Comment by SanderEST** [comment]
Oh, my bad! Did not notice the join function! Sorry! Anyways, pyranges is really great! Huge thanks for developing this!
