### ISSUE TITLE
Suffix is not applied to Strand when joining unstranded and stranded ranges

### ISSUE THREAD

**Issue by alecchap** [biocore-ntnu/pyranges#215]
In the code below, although the treatment of 'Strand' is consistent with other columns that don't have overlapping names, it seems like it would be more correct to rename it to 'Strand_b'.  With the current behavior, the intervals in `gr1` receive the strand information from `gr2`, which was quite unexpected in my case.

If breaking existing behavior is a concern, one possibility would be to raise a warning and add a flag to `join` like `apply_strand_suffix` that defaults to `None` and has the current behavior, but suppresses the warning by specifying `True` or `False`.

```
>>> gr1 = pr.from_dict({'Chromosome': ['chr1', 'chr1'], 'Start': [2, 9], 'End': [5, 12]})
>>> gr2 = pr.from_dict({'Chromosome': ['chr1', 'chr1'], 'Start': [1, 2], 'End': [6, 7], 'Strand': ['+', '-']})
>>> gr1.join(gr2)
+--------------+-----------+-----------+-----------+-----------+--------------+
| Chromosome   |     Start |       End |   Start_b |     End_b | Strand       |
| (category)   |   (int32) |   (int32) |   (int32) |   (int32) | (category)   |
|--------------+-----------+-----------+-----------+-----------+--------------|
| chr1         |         2 |         5 |         1 |         6 | +            |
| chr1         |         2 |         5 |         2 |         7 | -            |
+--------------+-----------+-----------+-----------+-----------+--------------+
Stranded PyRanges object has 2 rows and 6 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome and Strand.

```

**Comment by endrebak** [comment]
Perhaps this is unexpected:

```
   ...: >>> gr1.intersect(gr2)
+--------------+-----------+-----------+
| Chromosome   |     Start |       End |
| (category)   |   (int32) |   (int32) |
|--------------+-----------+-----------|
| chr1         |         2 |         5 |
| chr1         |         2 |         5 |
+--------------+-----------+-----------+
Unstranded PyRanges object has 2 rows and 3 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome.

   ...: >>> gr2.intersect(gr1)
+--------------+-----------+-----------+--------------+
| Chromosome   |     Start |       End | Strand       |
| (category)   |   (int32) |   (int32) | (category)   |
|--------------+-----------+-----------+--------------|
| chr1         |         2 |         5 | +            |
| chr1         |         2 |         5 | -            |
+--------------+-----------+-----------+--------------+
Stranded PyRanges object has 2 rows and 4 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome and Strand.
```

However, the problem here is that if I call the column `Strand_b` the new Pyranges won't be stranded even though it contains strand data. This is even more unexpected, or at least it would be so for me.

You can fix this by 

```
gr = gr2.join(gr1)
gr.columns = gr.columns.str.replace("Strand", "Strand_b")
```

but you probably know that.

**Comment by endrebak** [comment]
I really appreciate you making all these issues btw :) 👍

**Comment by endrebak** [comment]
I like your idea for a fix btw :)

**Comment by endrebak** [comment]
Might `other_strand_as_data` be a more descriptive name? Choosing names is hard

**Comment by endrebak** [comment]
Fixed in 0.0.107

**Comment by alecchap** [comment]
Looks like a typo snuck in.  I'm getting an error importing pyranges:

```
>>> import pyranges
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/pyranges/__init__.py", line 358, in <module>
    from pyranges.readers import read_bam, read_bed, read_bigwig, read_gff3
  File "/usr/local/lib/python3.9/site-packages/pyranges/readers.py", line 190
    0                               "0.0.5", "0.0.6", "0.0.7", "0.0.8", "0.0.9"]:
                                    ^
SyntaxError: invalid syntax

```

**Comment by alecchap** [comment]
FWIW, the `insert` behavior feels expected to me.  I guess I tend to think of Chromosome/Start/End/Strand as one logical unit, so mixing the strand from one interval with the coordinates from another seems weird.  `other_strand_as_data` sounds good to me as it reinforces that logical separation between the interval and its associated data.

In my use case, `gr1` was a list of unstranded enhancer regions, `gr2` was a list of gene annotations, and I was doing the join with a large slack.  I was thinking of the result as still representing the enhancers but with some added information about the neighboring genes, but it seemed wrong for the strand of the gene to be applied to the (nonoverlapping) enhancer.  I imagine there are also cases where one would do the join in order to gain strand information.
