### ISSUE TITLE
SyntaxError originating from a typo in pyranges.readers

### ISSUE THREAD

**Issue by haimasree** [biocore-ntnu/pyranges#218]
In the most recent pypi release [this](https://github.com/biocore-ntnu/pyranges/blob/master/pyranges/readers.py#L190) is causing syntaxerror.
```
E     File "/usr/share/miniconda/envs/kipoi-veff2/lib/python3.6/site-packages/pyranges/readers.py", line 190
E       0                               "0.0.5", "0.0.6", "0.0.7", "0.0.8", "0.0.9"]:
E                                             ^
E   SyntaxError: invalid syntax
```
As it is rather an easy fix, I am happy to provide a pr. Let me know!

**Comment by endrebak** [comment]
Will fix, thanks!

I hate that Travis-ci org stopped working

**Comment by endrebak** [comment]
Quickfix during lunch break :) 0.0.108 is out

**Comment by haimasree** [comment]
> Quickfix during lunch break :) 0.0.108 is out
Great! Thanks for your prompt response 👍
