### ISSUE TITLE
Behaviour of gr.merge

### ISSUE THREAD

**Issue by peterch405** [biocore-ntnu/pyranges#22]
I have been testing gr overlap and merge functions. As far as I can tell right now overlap works by not considering the end (1,5] while merge works by considering it (1,5)?

I have this example bellow:

```
import pyranges as pr
from pyranges import PyRanges

import pandas as pd

from io import StringIO

f1 = """Chromosome Start End Score Strand
chr1 4 7 23.8 +
chr1 6 11 0.13 -
chr2 0 14 42.42 +"""


df1 = pd.read_csv(StringIO(f1), sep="\s+")

gr1 = PyRanges(df1)

f2 = """Chromosome Start End Score Strand
chr2 14 18 15.3 +
"""


df2 = pd.read_csv(StringIO(f2), sep="\s+")

gr2 = PyRanges(df2)

gr1.overlap(gr2)

f3 = """Chromosome Start End Score Strand
chr1 4 7 23.8 +
chr1 6 11 0.13 -
chr2 0 14 42.42 +
chr2 14 18 15.3 +"""


df3 = pd.read_csv(StringIO(f3), sep="\s+")

gr3 = PyRanges(df3)

gr3.merge(count=True)
```

overlap doesn't produce any overlaps while merge merges the intervals that start and end with the same coordinate. Personally I would have expected the two to work the same way. Is there a way to get the same results from merge as you get from overlap?

**Comment by endrebak** [comment]
This is a bug on my end. I would want the same behaviour as you expect. I’ll look into it today :)

**Comment by endrebak** [comment]
Thanks for reporting btw :)

**Comment by endrebak** [comment]
I answered prematurely, right after waking up XD. I imagined you wrote `cluster` and `merge` should behave the same way. 

You can avoid merging bookended features with the slack argument:

```
gr = PyRanges(chromosomes="chr1 chr1".split(), starts=[5, 10], ends=[10, 15])
# +--------------+-----------+-----------+
# | Chromosome   |     Start |       End |
# | (category)   |   (int32) |   (int32) |
# |--------------+-----------+-----------|
# | chr1         |         5 |        10 |
# | chr1         |        10 |        15 |
# +--------------+-----------+-----------+
# Unstranded PyRanges object has 2 rows and 3 columns from 1 chromosomes.
gr.merge(slack=-1) # or gr.cluster
# +--------------+-----------+-----------+
# | Chromosome   |     Start |       End |
# | (category)   |   (int32) |   (int32) |
# |--------------+-----------+-----------|
# | chr1         |         5 |        10 |
# | chr1         |        10 |        15 |
# +--------------+-----------+-----------+
# Unstranded PyRanges object has 2 rows and 3 columns from 1 chromosomes.
```

This was not my intention, but it seems to work. 

[bedtools](https://bedtools.readthedocs.io/en/latest/content/tools/merge.html) also merges bookended features.

**Comment by endrebak** [comment]
I was not either :) I actually made it for positive values :)
