### ISSUE TITLE
pyranges Subtract does not work in pyranges v0.0.110 

### ISSUE THREAD

**Issue by mikecormier** [biocore-ntnu/pyranges#224]
The **Subtract** method does not work with the latest version of pyranges. 

The problem stems from a change in a newer version of the NCLS module. 

I am not sure which version of NCLS is causing the problem.

NCLS version `0.0.53` works.

NCLS version `0.0.62` does not. 

Error traceback: 
```
File "/lib/python3.8/site-packages/pyranges/methods/subtraction.py", line 64, in _subtraction
    idx_self, new_starts, new_ends = o.set_difference_helper(
  File "ncls/src/ncls32.pyx", line 450, in ncls.src.ncls32.NCLS32.set_difference_helper
TypeError: set_difference_helper() takes exactly 3 positional arguments (4 given)
```

**Comment by endrebak** [comment]
You should update NCLS. I should have required a minimum NCLS version in pyranges. Will fix tonight.

thanks!

**Comment by fransua** [comment]
Yes!
thanks @endrebak !
side-note: after my dirty fix I was also noticing a weird behavior each 1024 rows??? ... I guess my fix was really dirty

thanks a lot for the software!

**Comment by endrebak** [comment]
The old NCLS had a bug: it only found the first 1024 intervals of overlap.
That might explain it.

Thanks for reporting and testing all of you :)
