### ISSUE TITLE
The __init__.py file of pyranges 0.0.52 on pypi is empty

### ISSUE THREAD

**Issue by s6juncheng** [biocore-ntnu/pyranges#23]
As stated, use the `__init__.py` file from this github repo fix the problem. But the distributed file on pypi has an empty `__init__.py`

**Comment by endrebak** [comment]
Thanks for reporting! Tried to fix this in 0.0.53.

**Comment by endrebak** [comment]
The init in 0.0.53 is > zero bytes so this is fixed :) Thanks for bothering to report this :) 👍
