### ISSUE TITLE
to_gff3 output not readable by read_gff3

### ISSUE THREAD

**Issue by augustboyle** [biocore-ntnu/pyranges#231]
Hello, when I read in a GENCODE GFF3 file, subset it, and write it out with to_gff3, I am unable to read the output file (even if no entries have been removed) a second time.

I get a ValueError when I try to read the file
`ValueError: not enough values to unpack (expected 2, got 1)`

The issue seems to be that there is a spare semicolon added to the end of the line in to_gff3, which read_gff3 then tries to unpack, unsuccessfully. It seems like this extra semicolon needs to be stripped before writing.

**Comment by endrebak** [comment]
Thanks! This is actually a good sanity-check. Test the roundtrip from reading to writing. 

Will fix within a week probably :)

**Comment by endrebak** [comment]
I'll look at this the 21 of December :)

**Comment by endrebak** [comment]
So the reader is correct, but the writer is wrong: https://m.ensembl.org/info/website/upload/gff3.html

**Comment by endrebak** [comment]
But gtf ends with a ; XD https://www.ensembl.org/info/website/upload/gff.html

**Comment by endrebak** [comment]
It should be done now. See 0.0.115. Thanks for reporting and sorry about the tardiness.
