### ISSUE TITLE
Request for tutorial for beginners

### ISSUE THREAD

**Issue by mnshgl0110** [biocore-ntnu/pyranges#234]
Hi,

I would like to try pyranges and incorporate it in my pipelines. But I can't find any tutorial for beginners to get started with it. Something that could quickly explain and provide example code for the most important tasks like reading data and creating the range object, finding overlaps between two range-objects, merge/intersect ranges etc.

Does such a tutorial exists? If so, then could you please share it.

I understand that it is possible to figure these things out from the API reference but that would require much more time and is a bit difficult for the uninitiated. Given the tremendous potential of pyranges in improving genomics analysis in python, I think it would be extremely helpful to have tutorials to decrease the time required to find the solutions and also to make it more friendly to new users.

Best
Manish

**Comment by endrebak** [comment]
I'll think about it. Good suggestion.

At least something like https://learnxinyminutes.com/ would be nice, eg
https://learnxinyminutes.com/docs/python/

**Comment by mnshgl0110** [comment]
Actually, an excellent starting point would be the guides from the [genomicranges package](https://bioconductor.org/packages/release/bioc/html/GenomicRanges.html). Modifying the introduction and the HowTos there for pyranges would already be a quite comprehensive resource.

**Comment by endrebak** [comment]
Read the Rmd files. I'll get around to creating a proper page from these soon

https://github.com/endrebak/pyranges_book

**Comment by mnshgl0110** [comment]
Great and thanks a lot. Looking forward to the finished documentation.

**Comment by endrebak** [comment]
I'll probably won't get around to doing that before after Xmas. But thanks
for your suggestion. Feedback on the book is also welcome.

If you have questions about PyRanges, feel free to ask here or on Stack
Overflow

**Comment by endrebak** [comment]
Note to self: 

try this action to build the book automatically upon pushing https://github.com/marketplace/actions/deploy-to-github-pages
