### ISSUE TITLE
possible bug joining int64 ranges

### ISSUE THREAD

**Issue by rwaples** [biocore-ntnu/pyranges#24]
I was happy to see this package, thank you.

I am getting failed joins when using long ranges (ie that cover the genome rather than a chromosome)

```
import pyranges as pr
import pandas as pd
a = pr.PyRanges(pd.DataFrame(data = {'Chromosome':  [0], 'Start':[0], 'End': 5e10}), int64=True)
b = pr.PyRanges(pd.DataFrame(data = {'Chromosome':  [0, 0], 'Start':[0, 5], 'End': [5, 5e10]}), int64=True)
a.join(b)
```
produces:
`Empty PyRanges
`

I expect it to produce the same as below

```
a = pr.PyRanges(pd.DataFrame(data = {'Chromosome':  [0], 'Start':[0], 'End': 5e8}), int64=True)
b = pr.PyRanges(pd.DataFrame(data = {'Chromosome':  [0, 0], 'Start':[0, 5], 'End': [5, 5e8]}), int64=True)
a.join(b)
```
which produces
```
+--------------+-----------+-----------+-----------+-----------+
|   Chromosome |     Start |       End |   Start_b |     End_b |
|   (category) |   (int64) |   (int64) |   (int64) |   (int64) |
|--------------+-----------+-----------+-----------+-----------|
|            0 |         0 | 500000000 |         0 |         5 |
|            0 |         0 | 500000000 |         5 | 500000000 |
+--------------+-----------+-----------+-----------+-----------+
Unstranded PyRanges object has 2 rows and 5 columns from 1 chromosomes.
```

Python version 3.7.4
pyranges version 0.0.54

```

**Comment by endrebak** [comment]
I have realised that my int64-implementation is buggy. I have created an issue #25 about this and will fix it within the next week. If you still are considering using PyRanges you could use int(1e9) until I fix it and then just update the code you write with int(1e10) later. Thanks again for reporting :)

**Comment by rwaples** [comment]
Thanks for the update.

**Comment by endrebak** [comment]
If you update sorted_nearest (a pyranges-requirement), pyranges with int64 should work now.

For simulations, `pyranges.random` might be of use:

```
import pyranges as pr
from numpy.random import seed
seed(0)
gr = pr.random(100, length=1, chromsizes=pr.PyRanges(starts=[0], ends=[int(1e10)], chromosomes=[0], int64=True), int64=True)
```

Note that the int64 flag to random was added in `0.0.55`.
