### ISSUE TITLE
PyRanges.join() and match columns as well as genomic range

### ISSUE THREAD

**Issue by fairliereese** [biocore-ntnu/pyranges#259]
I'm trying to assign regions from one PyRanges object to those that are defined in another.  What I would like to do is merge using `PyRanges.join()`both on genomic region as well as on metadata columns that match across the two datasets (in a similar manner to how `PyRanges.cluster()` or `PyRanges.merge()` operate). 

Here's a small example:

```python
import pyranges

starts = [1, 10, 20]
ends = [15, 12, 25]
chroms = [1, 1, 1]
gids = ['gene_1', 'gene_2', 'gene_2']
gr = pyranges.PyRanges(chromosomes=chroms, starts=starts, ends=ends).as_df()
gr['gene_id'] = gids
gr = pyranges.PyRanges(df=gr)

starts = [11, 11]
ends = [11, 11]
chroms = [1, 1]
gids = ['gene_1', 'gene_2']
gr2 = pyranges.PyRanges(chromosomes=chroms, starts=starts, ends=ends).as_df()
gr2['gene_id'] = gids
gr2 = pyranges.PyRanges(df=gr2)

gr2.join(gr, how='left', strandedness=None)
```

Here are the tables and what the result of what I can achieve with join looks like:
![Screen Shot 2022-02-23 at 5 39 12 PM](https://user-images.githubusercontent.com/21128281/155440695-447bf54a-da22-4a89-bb42-3e97943cd368.png)

And here is what I would like the output from changing this function and possibly what the call would look like, similarly to how pandas joins work:
```python
gr2.join(gr, how='left', strandedness=None, on=['gene_id'])
```

![Screen Shot 2022-02-23 at 5 41 52 PM](https://user-images.githubusercontent.com/21128281/155440970-4a7953fe-5383-427b-ac16-3f7f83d43869.png)

This is a simplified example but I can imagine that this would be useful to some people! And if this is already possible with a different function I'm not seeing, I'd love to know.

**Comment by endrebak** [comment]
Thanks for asking :D 

I think this is possible to do as two operations:

```
j = gr2.join(gr)
j[j.gene_id == j.gene_id_b]

# +--------------+-----------+-----------+------------+-----------+-----------+-------------+
# |   Chromosome |     Start |       End | gene_id    |   Start_b |     End_b | gene_id_b   |
# |   (category) |   (int32) |   (int32) | (object)   |   (int32) |   (int32) | (object)    |
# |--------------+-----------+-----------+------------+-----------+-----------+-------------|
# |            1 |        11 |        11 | gene_1     |         1 |        15 | gene_1      |
# |            1 |        11 |        11 | gene_2     |        10 |        12 | gene_2      |
# +--------------+-----------+-----------+------------+-----------+-----------+-------------+
# Unstranded PyRanges object has 2 rows and 7 columns from 1 chromosomes.
# For printing, the PyRanges was sorted on Chromosome.
```

If you do not know the subsetting syntax it is not easy to do though. Is the above approach ok with you or is there something you miss?

**Comment by fairliereese** [comment]
Hi! Thanks, I'm not sure how I didn't think of this as a solution. I think this will work for me, but I can imagine that for large datasets with a lot of overlaps the matrix that results from the join operation might be prohibitively large, in which case it might still be a good idea to implement an option like this! Either way I hope this issue might help others with the same problem!

**Comment by endrebak** [comment]
Yes, I've been thinking of creating a recipe collection for PyRanges. Many things are simple to do with a few operations, but it might not be obvious how to do so without a good familiarity with the API.

**Comment by fairliereese** [comment]
Ah I actually realize why your solution is actually directly incompatible with what I need -- I need the inverse of what already overlaps with a specific region / set of columns. With your approach, query regions that are duplicated or overlap but with different identifying columns will be even further duplicated if there are extra overlapping regions in the reference dataset.

**Comment by endrebak** [comment]
If you post an example I'm sure I can help. I did solve your stated problem and I'm sure I can do so again :)

If this is something that is hard to do given the current operations I'll add support for it.
