### ISSUE TITLE
Replace parameter is ignored in PyRanges.sample

### ISSUE THREAD

**Issue by FabrizioG202** [biocore-ntnu/pyranges#267]
The replace parameter in PyRanges.sample is ignored:
https://github.com/biocore-ntnu/pyranges/blob/master/pyranges/pyranges.py#L3660-L3663

While it's possible to pass replace=True to the sample function, its implementation always use replace=False

**Comment by endrebak** [comment]
Thanks. Ill get around to fixing it soon. Unless you want to make a simple
PR?

Endre

**Comment by FabrizioG202** [comment]
I made the simple PR but I had never done it before so I hope everything is as it should:
https://github.com/biocore-ntnu/pyranges/pull/270

**Comment by endrebak** [comment]
Thanks for the help! Closing :D
