### ISSUE TITLE
Ranges disappear when get out of bounds on the 5' end in spliced_subsequence

### ISSUE THREAD

**Issue by JoanPAAL** [biocore-ntnu/pyranges#285]
@marco-mariotti  

""" This little script should show how ranges disappear when get out of bounds on the 5' end in spliced_subsequence
     This does not happen when using subsequence()       
"""

import pyranges as pr

p = pr.from_dict({"Chromosome": [1,1], "Strand": ["+","-"], 
                  "Start": [0,0], "End": [62,62], 
                  "transcript_id": ["t1","t2"]})

print('This is p:\n',p)

pe = p.extend({"3":900}, group_by="transcript_id")

print('This is extended p:\n',pe)

ps = pe.subsequence(-900,by="transcript_id")

print('This is ps (subsequenced):\n',ps)

pss = pe.spliced_subsequence(-900,group_by="transcript_id")

print('This is pss (spliced_subsequenced):\n',pss)

**Comment by marco-mariotti** [comment]
Fixed in https://github.com/biocore-ntnu/pyranges/pull/294

**Comment by endrebak** [comment]
Thanks for reporting the bug, and thanks to Marco for fixing it. It should be fixed in the latest pyranges. Feel free to reopen if something is not working as expected.
