### ISSUE TITLE
[Feature request] Incorporate inplace parameter in drop() method

### ISSUE THREAD

**Issue by maxtico** [biocore-ntnu/pyranges#288]
I'm a common user of PyRanges. Sometimes, when I work with GFF3 files, I need to discard some specific columns. To do so, I always use PyRanges.drop(drop='column') method.

However, I always need to save the output in a new variable since it doesn't offer a way to drop columns in place. It would be great to be able to drop columns mutating the actual PyRanges, without returning it.

As an example, I really like panda's inplace=True keyword, which modifies the data without returning anything.

**Comment by endrebak** [comment]
You can do

`gr = read_gtf(f).drop(col_names)`

I'm not a fan of using the `inplace` argument myself. Less mutability is always better IMO.
