### ISSUE TITLE
overlap() return an empty object

### ISSUE THREAD

**Issue by axol0tl** [biocore-ntnu/pyranges#289]
Hi,

my issue is with overlap() function

my genomic regions are pyranges `bed` :
+--------------+-----------+-----------+------------+-----------+-----------+
| Chromosome   | Start     | End       | Name       | Score     | i         |
| (category)   | (int32)   | (int32)   | (object)   | (int64)   | (int64)   |
|--------------+-----------+-----------+------------+-----------+-----------|
| 1            | 10054     | 10182     | c1         | 0         | 0         |
| 1            | 10182     | 10310     | c2         | 0         | 1         |
| 1            | 10310     | 10438     | c3         | 0         | 2         |
| 1            | 10438     | 10566     | c4         | 0         | 3         |
| ...          | ...       | ...       | ...        | ...       | ...       |
| X            | 156030363 | 156030491 | c7432941   | 0         | 8182881   |
| X            | 156030491 | 156030619 | c7432942   | 0         | 8182882   |
| X            | 156030619 | 156030747 | c7432943   | 0         | 8182883   |
| X            | 156030747 | 156030875 | c7432944   | 0         | 8182884   |
+--------------+-----------+-----------+------------+-----------+-----------+

and the desired region to find overlaps with is `query_ranges` :
+--------------+-----------+-----------+
|   Chromosome |     Start |       End |
|   (category) |   (int32) |   (int32) |
|--------------+-----------+-----------|
|            1 |         0 |   1000000 |
+--------------+-----------+-----------+

when i do `bed.overlap(query_ranges)` i get `--` . Same happens with intersect()

It really puzzles me. I checked the bed object and it does not have Nan values, both objects are PyRanges objects, there are clearly some regions in bed that could be found within chr1 from 0 to 1000000

Does anybody have any idea what is wrong?

Thanks!

**Comment by marco-mariotti** [comment]
Perhaps Chromosome is not exactly the same? Do you have spaces or tabs or something like that?
If not, please provide data to reproduce the error

**Comment by endrebak** [comment]
Without a reproducible example I cannot help you unfortunately.

Feel free to reopen if you have a reproducible example.
