### ISSUE TITLE
Cannot convert non-finite values (NA or inf) to integer

### ISSUE THREAD

**Issue by seven1112233** [biocore-ntnu/pyranges#307]
hi,
when I load gtf file from gencode using pyranges.read_gtf, i got an error"ValueError: Cannot convert non-finite values (NA or inf) to integer". the version of pyranges is 0.0.124. could you help me fix this error? Thank you very much!
![image](https://user-images.githubusercontent.com/71070001/236623833-6ad988e9-efdf-4c4d-afc6-f203bfe0f287.png)

**Comment by hiraksarkar** [comment]
Getting the same error.

**Comment by DongzeHE** [comment]
Same error.

**Comment by DongzeHE** [comment]
I used this reference from 10x Genomics. https://support.10xgenomics.com/single-cell-gene-expression/software/downloads/latest#:~:text=References%20%2D%202020%2DA%20(July%207%2C%202020)

**Comment by seven1112233** [comment]
Thank you for your reply.
the gtf file I used is download from gencode and without any modification.
human gtf from gencode: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_43/GRCh37_mapping/gencode.v43lift37.annotation.gtf.gz


Dinasour
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "biocore-ntnu/pyranges"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月9日(星期二) 晚上11:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [biocore-ntnu/pyranges] Cannot convert non-finite values (NA or inf) to integer (Issue #307)





 
Do any of you have some example data? I cannot reproduce

**Comment by endrebak** [comment]
Was able to reproduce with human gencode. Will fix now.

**Comment by seven1112233** [comment]
it seems that rows number in file cannot more than 100,000, otherwise we will get error

**Comment by endrebak** [comment]
I will fix but the error does not seem to be inexplicable.

This is the code where the error shows up:

```python
    df_iter = pd.read_csv(
        f,
        sep="\t",
        header=None,
        names=names,
        dtype=dtypes,
        chunksize=int(1e5),
        skiprows=skiprows,
        nrows=nrows,
    )

    _to_rows = to_rows_keep_duplicates if duplicate_attr else to_rows
    dfs = []
    for df in df_iter:
        extra = _to_rows(df.Attribute, ignore_bad=ignore_bad)
        df = df.drop("Attribute", axis=1)
        ndf = pd.concat([df, extra], axis=1, sort=False)
        dfs.append(ndf)
```

The first iteration the Start/End dtypes are correct, the second they become `float64`.
