### ISSUE TITLE
Exception: ('PyRanges object has no attribute', '__getstate__') when run in parallel

### ISSUE THREAD

**Issue by cfriedline** [biocore-ntnu/pyranges#40]
Hi @endrebak. Another snag I ran into. We have a large number of ranges we are processing, and it would be great to be able to do this in parallel. Some of our processing is fast, but for other situations it could take up to an hour or more to get all of the records processed. A use case to consider is iterating a VCF file and for each record, determining transcript and exon overlaps from PyRanges objects which contain this information. I'd like to be able to parallelize sending the overlap calls for each record in the VCF. However, the PyRanges objects can't be pickled in their current state. 

Here's a trivial example, with some code to show the parallel syntax working. 

```
# %%
import pyranges as pr
gr = pr.data.chipseq()

# %%
from joblib import Parallel, delayed


# %%
def overlap(source, target):
    return target.overlap(source)

def test(t):
    return t

samples = [pr.PyRanges(gr.df.sample()) for i in range(10)]     

# %%
with Parallel(n_jobs=8) as par:
    results = par((delayed(test)(i) for i in range(10)))
results

# %%
with Parallel(n_jobs=8) as par:
    results = par((delayed(overlap)(gr, s) for s in samples))
results
```

I will concede that there may be a better way to do this. Some info on the underlying data:

* exons: `Stranded PyRanges object has 790,511 rows and 19 columns from 25 chromosomes`
* transcripts: `Stranded PyRanges object has 77,825 rows and 19 columns from 25 chromosomes.`

When searching exons, I do filter the ranges first by transcript to speed things up, and doing this on a record-by-record basis in parallel would be better.

Any way it would be possible to make PyRanges objects pickleable?

Thanks very much!
Chris

**Comment by endrebak** [comment]
A PyRange is basically a python dict of dataframes, both of which are pickleable.

```
import pyranges as pr
gr = pr.data.exons()
dfs = gr.dfs
print("Pickle these:", dfs)
print("Then create a Pyranges from the dict easily, with no overhead:", pr.PyRanges(dfs))
```

But anyways, PyRanges is multithreaded. Have you tried `gr.overlap(gr2, nb_cpu=len(gr.dfs))`?

You can also use `apply` or `apply_pair` with `nb_cpu` if you require custom functions to be multithreaded.

How do you filter the transcripts? The `gr["chr1", "+", 50:100]` syntax is convenient, but slow as it builds an NCLS for every query... It should be avoided in loops.

**Comment by endrebak** [comment]
But I am keeping this open as pickling PyRanges is trivial. I wonder whether I should do it as pickle is only used for multithreading, which is much slower with joblib or multiprocessing than ray, which PyRanges uses.

**Comment by endrebak** [comment]
I assume this solved your problem, otherwise feel free to reopen or create a new thread. 

If any of you people are coming to https://meetings.cshl.edu/meetings.aspx?meet=info&year=19, I would love to talk to you about pain points or answer whatever questions about pyranges :)

**Comment by cfriedline** [comment]
Thanks for your comments. I have made changes to my underlying code, doing nearly all of the overlapping up front and then processing the resulting data frames. However, there are still areas in my code which could be optimized by multiprocessing which are not possible currently because of the `__get_state__` issue. For example, I have classes which maintain PyRanges objects behind an api that would need to be serialized to worker processes.

**Comment by endrebak** [comment]
Have created a branch for this, will merge when passes. Feel free to check it out @ make_pickleable.

Note that the built-in parallelization offered by ray is copy-free and much faster :)

**Comment by cfriedline** [comment]
Thanks! While bulk overlapping (with nb_cpu) is most performant, especially for large queries, there are definitely cases in my own code where being able to send groups of ranges off for further processing to workers is a valid use-case. Looking forward to testing it out. There is still serialization with ray, but I get your point.

**Comment by endrebak** [comment]
This should be fixed in 0.0.58

If you have suggestions for different kinds of multithreading, I'd be happy to mull them over. I currently have `apply` (single PyRanges), `apply_pair` (pairs of PyRanges) and `apply_chunks` (single PyRanges, where the function applied is row-based).

**Comment by cfriedline** [comment]
> If you have suggestions for different kinds of multithreading, I'd be happy to mull them over. I currently have `apply` (single PyRanges), `apply_pair` (pairs of PyRanges) and `apply_chunks` (single PyRanges, where the function applied is row-based).

I do find myself dragging along a bunch of metadata (e.g., transcript names, exon indexes, hgnc ids, primary keys for later use) and have sometimes needed to compute on those fields. For this, I drop to `.df` do the `groupby.apply()` and then go back to a PyRanges object. It would be sweet if I could just do something like `apply_by(fn, fields=...)` and maybe even `apply_chunks_by(f, fields=...)` to do it by rows. Not a big deal, and I don't think you want to (or should try to) mirror all of pandas functionality, but this might useful when you want to compute on ranges and get ranges back. Just a thought.

Thanks again for being so responsive to these issues!

**Comment by endrebak** [comment]
Thanks. If you could write a tiny example, it would be immensely helpful :)

**Comment by endrebak** [comment]
Here is an example that does something like what I think you might be
looking for:

https://stackoverflow.com/a/58538110/992687

Note that when you use the .df property, pandas concat, is called, which
might be expensive for large dfs with object/str columns. It is better to
use a gr.apply like in the example in the link :)

Endre
