### ISSUE TITLE
Different results with join in 0.0.57

### ISSUE THREAD

**Issue by cfriedline** [biocore-ntnu/pyranges#48]
Prior to 0.0.57, the files I am processing produce much larger PyRanges objects. However, when I upgrade to 0.0.57, the ranges are much smaller and cause our pipeline to crash. I'm happy to share files offline, but can't post them here.

For example, in 0.0.56 (and 0.0.55), I log this:
```
2019-10-23 14:00:52,481|processor.processor|process|769|INFO|Processing 8577 exon overlaps from 16 segments in 964 transcripts of 355 genes
```

With the same files and code, but after upgrading to 0.0.57, this is logged.

```
2019-10-23 14:05:06,403|processor.processor|process|769|INFO|Processing 17 exon overlaps from 3 segments in 11 transcripts of 3 genes
```

The method in question is here:

```
def get_exon_join(self, other: PyRanges, flip: bool = True) -> PyRanges:
    """
    Join ranges, other, with exon ranges. If flip is false, the join
    is done with other as the target, rather than the source
    :param other: the ranges to join
    :param flip: if true, other is first. if false, other is second
    :return: a pyranges object
    """
    other.Chromosome = other.df.Chromosome.apply(self.get_target_contig_name)
    if flip:
        return other.join(self._exon_ranges, suffix="_exon")
    return self._exon_ranges.join(other, suffix="_other")
```

Has anything changed with respect to join in this regard? I've tried messing with `new_pos` with no success.

Thanks so much for taking a look!

**Comment by cfriedline** [comment]
Going further, this seems to have resolved it. Perhaps it has to do with the reindexing that you do on `.df`?

```
def get_exon_join(self, other: PyRanges, flip: bool = True) -> PyRanges:
    """
    Join ranges, other, with exon ranges. If flip is false, the join
    is done with other as the target, rather than the source
    :param other: the ranges to join
    :param flip: if true, other is first. if false, other is second
    :return: a pyranges objects
    """
    other_df = other.df
    other_df.Chromosome = other_df.Chromosome.apply(self.get_target_contig_name)
    other2 = PyRanges(other_df)
    if flip:
        return other2.join(self._exon_ranges, suffix="_exon")
    return self._exon_ranges.join(other2, suffix="_other")
```

**Comment by endrebak** [comment]
I want to keep potentially breaking changes as close to 0 as possible, and not introduce them after the beta is over. 

I really was bummed out to hear I broke your code :/

**Comment by cfriedline** [comment]
Thanks for the sympathy, but yes, I definitely did track it down and fix it. I was dropping to that df unnecessarily anyway, so I don't think it was a problem on your end, but mine. I agree that the reindexing is a good idea, and I'm glad to be able to track your latest versions as we develop our pipeline.
