### ISSUE TITLE
Printing the files after writing them out is slightly annoying in the REPL

### ISSUE THREAD

**Issue by endrebak** [biocore-ntnu/pyranges#52]
Being able to do `gr.to_csv("bla").cluster()` is convenient for storing the intermediate results in a call chain to view them later, but it is annoying to have the pyranges printed when just doing 

```
gr.to_gff3("bla")
```

in the REPL.

Solutions? 

I could add a chain-flag to the `to_*` methods. I guess this is the most Pythonic way, as it is explicit.

```
gr.to_gff3("bla", chain=False)
```

is kinda verbose though.

There are ways to know whether you are in an interactive interpreter or not, but I do not see how to use them to turn off printing in the specific case of writing a pyrange to a file.

**Comment by tzuni** [comment]
Is this really a common use case? I just would not have thought to do this. It feels to me to be against the logic of the `to_<filetype>` methods. At least taking a queue from the pandas implementations they don't return anything unless the filename or buffer is `None` then it returns the formatted data as a string. So still converting to csv or whatever in the case something is returned.

Though if it is a useful feature, maybe turning it around to have `chain` default to False feels better. Alternately maybe a seperate method name pattern like `fork_to_*` would get the intent across better?

**Comment by endrebak** [comment]
Yes, changing it to False by default is the best option. I hate introducing breaking changes, but I do not think this will break any existing code :)

**Comment by endrebak** [comment]
Added chain flag, set to False by default :)
