### ISSUE TITLE
Use `AttributeError` rather than plain `Exception`

### ISSUE THREAD

**Issue by MuhammedHasan** [biocore-ntnu/pyranges#54]
https://github.com/biocore-ntnu/pyranges/blob/570d34e1f66087512da771efe26dd04584fd9f04/pyranges/methods/attr.py#L56

In current behavior, built-in methods such as `hasattr` do not work because of wrong exception type.

**Comment by endrebak** [comment]
Thanks. I might have run into problems relating to this earlier. 

If you fork and create a PR you will be listed as a contributor on github, but if you do not care I can fix it :)
