### ISSUE TITLE
genomic features tss not working with GTF source

### ISSUE THREAD

**Issue by tzuni** [biocore-ntnu/pyranges#76]
I ran across this bug trying to use the `features.tss()` method. After doing some research the problem seems to be that this code was written expecting GFF column names which are different if the source is GTF.

In genomicfeatures.py the [`tss()` definition](https://github.com/biocore-ntnu/pyranges/blob/7d02b3c2cddbd6a8421869c50d4ca0b4570287b8/pyranges/genomicfeatures/genomicfeatures.py#L286) includes this line:

```python
df = df.drop(["ExonNumber", "ExonID"], 1)
```
But if my features are read from a gtf file (either by myself or using pyranges_db from gencode) the corresponding columns are actually called `['exon_number', 'exon_id']`. This is in contrast to what the columns are called when parsed from GFF files.

It looks like this is also the case with [`tes()`](https://github.com/biocore-ntnu/pyranges/blob/7d02b3c2cddbd6a8421869c50d4ca0b4570287b8/pyranges/genomicfeatures/genomicfeatures.py#L305)

Additionally, in looking at the code it looks like the `drop_duplicates` argument to `tss` and `tes` doesn't actually have any effect if you set this to `False`. It's true you would disable the drop duplicates statement at this level, but two calls deeper in `_tss()` and `_tes()` there is another drop_duplicates argument which defaults to `True` and the argument does not get passed down through [`tss_or_tes()`](https://github.com/biocore-ntnu/pyranges/blob/7d02b3c2cddbd6a8421869c50d4ca0b4570287b8/pyranges/genomicfeatures/genomicfeatures.py#L113) to prevent duplicate dropping at this level.

**Comment by endrebak** [comment]
Thanks. I will try to push a fix today. I guess the best way to handle this is to look for both naming conventions. I will also let the user select the ExonNumber and ExonID column so the method can be used on arbitrary genomic data.

I will have a look at the drop_duplicates issue too. Thanks for looking into it :)

**Comment by endrebak** [comment]
Will have to do this next week, sorry. It is high on my list and I am grateful that you created the issue :)

**Comment by tzuni** [comment]
No problem! Always happy to help!

**Comment by endrebak** [comment]
The fix I've pushed is to give `gtf` files the same column names as `gff` files. There is no reason they should be different - it was just a mistake on my part.

Thanks for reporting. I have some other PRs for fixing the other stuff too :) I guess I will push them to Pypi tomorrow.

**Comment by endrebak** [comment]
Actually, my fix is now to use the names as-is from the attribute column of gffs/gtfs. I had no good reason to change them in the first place.

`gene_id` is now `gene_id`, not `GeneID`. I think my original intent was to show that these columns were of special interest since they were used for feature functionality, but it was a stupid idea.

**Comment by endrebak** [comment]
The (potentially breaking) fixes are out in `0.0.65`.
