### ISSUE TITLE
Keep QNAMES when reading BAM files

### ISSUE THREAD

**Issue by KerstenBreuer** [biocore-ntnu/pyranges#84]
Hi,

First of all, thanks a lot for the great package. This is exactly what the python ecosystem required.

It would be great, if the QNAME field of BAM files would be kept in the pyranges object when using the `read_bam` function. E.g. when working with paired end data, this is important to recover read pairs.

Thanks a lot

**Comment by endrebak** [comment]
Thanks for the kind words. I never read bam files myself so the function to do it is rather rudimentary. I will try to create a function that keeps the names this Friday.

Most of the other stuff you need you can get from the flag field, right? 

Is there other stuff in bam files you see yourself using in the future? I am not that familiar with them :)

**Comment by endrebak** [comment]
As of pyranges 0.0.66 you can use

`pr.read_bam(f, sparse=False, ...)` to get more columns, including qname :)
